<a href="https://colab.research.google.com/github/Sanchit525/ETF---Smart-Portfolio/blob/Test/ETF_Smart_Portfolio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import yfinance as yf
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
import pandas as pd
from pathlib import Path
import numpy as np

**Extracting tickers of all the etfs**

In [ ]:
etf_database = pd.read_csv("/content/MW-ETF-27-Jan-2026.csv")
etf_database.columns

Index(['SYMBOL \n', 'UNDERLYING ASSET \n', 'OPEN \n', 'HIGH \n', 'LOW \n',
       'PREV. CLOSE \n', 'LTP \n', 'INDICATIVE CLOSE \n', 'CHNG \n',
       '%CHNG \n', 'VOLUME \n', 'VALUE \n (₹ Crores)', 'NAV \n', '52W H \n',
       '52W L \n', '30D  %CHNG \n', '365 D   %CHNG \n'],
      dtype='object')

In [ ]:
tickers = etf_database["SYMBOL \n"].to_list()
tickers.insert(0,'NIFTY 50')
print(tickers)

['NIFTY 50', 'TATSILV', 'HDFCSILVER', 'SILVERAG', 'SILVERBETA', 'SBISILVER', 'AXISILVER', 'SILVERIETF', 'GROWWSLVR', 'SILVERCASE', 'SILVERBEES', 'SILVERADD', 'MOSILVER', 'SILVER', 'SILVER1', 'SILVERBND', 'ESILVER', 'SILVER360', 'HDFCMOMENT', 'EGOLD', 'GROWWN200', 'METALIETF', 'TWCGOLDETF', 'GOLDBND', 'GOLDETF', 'GROWWMETAL', 'CHOICEGOLD', 'TATAGOLD', 'HDFCPVTBAN', 'GROWWPOWER', 'GOLDIETF', 'GOLDBEES', 'IVZINGOLD', 'GROWWSC250', 'EVIETF', 'METAL', 'AXISGOLD', 'HDFCNEXT50', 'SETFGOLD', 'GOLDCASE', 'HDFCNIF100', 'GROWWNET', 'HDFCGOLD', 'HDFCQUAL', 'GOLD1', 'BSLGOLDETF', 'GOLDBETA', 'GROWWGOLD', 'QGOLDHALF', 'MOMENTUM30', 'GOLDADD', 'AONETMMQ50', 'AONEGOLD', 'GOLD360', 'MOGOLD', 'MODEFENCE', 'MOTOUR', 'AXISVALUE', 'GROWWDEFNC', 'PSUBNKBEES', 'COMMOIETF', 'BBNPPGOLD', 'HDFCPSUBK', 'SML100CASE', 'BANKPSU', 'SBIBPB', 'PSUBNKIETF', 'LICMFGOLD', 'PSUBANK', 'MANUFGBEES', 'MOVALUE', 'GROWWCAPM', 'BANKADD', 'CPSEETF', 'ELM250', 'BANKETF', 'ICICIB22', 'PSUBANKADD', 'MOCAPITAL', 'BANKIETF', 'HDFCNIFBAN', 'BBNPNBETF', 'TOP10ADD', 'BANKBETA', 'QUAL30IETF', 'DIVIDEND', 'BANKBEES', 'NIFTY100EW', 'BANKBETF', 'SETFNIFBK', 'MID150CASE', 'AXISBNKETF', 'ECAPINSURE', 'MOPSE', 'SBIETFIT', 'UNIONGOLD', 'NV20', 'NIF100BEES', 'PVTBANIETF', 'ITBEES', 'MOENERGY', 'BFSI', 'MONQ50', 'OILIETF', 'EMULTIMQ', 'ABSLPSE', 'BANKNIFTY1', 'SBIETFPB', 'ABSLBANETF', 'MONIFTY500', 'ITIETF', 'MOMOMENTUM', 'GROWWRAIL', 'MIDSMALL', 'NIFTYCASE', 'GROWWMC150', 'MID150', 'TOP100CASE', 'BSLNIFTY', 'PVTBANKADD', 'NEXT30ADD', 'AXISHCETF', 'ITETF', 'MOREALTY', 'MOMIDMTM', 'MAFANG', 'NEXT50', 'SBIETFQLTY', 'MOHEALTH', 'ENERGY', 'NV20BEES', 'MOM100', 'INFRABEES', 'MON50EQUAL', 'ABSLNN50ET', 'EQUAL200', 'MOINFRA', 'ITBETA', 'MIDCAPIETF', 'MULTICAP', 'MIDCAPBETA', 'JUNIORBEES', 'EQUAL50ADD', 'EBANKNIFTY', 'CHEMICAL', 'LICNFNHGP', 'MOSMALL250', 'HDFCSML250', 'SENSEXBETA', 'MID150BEES', 'HDFCNIFTY', 'MSCIINDIA', 'NV20IETF', 'INFRAIETF', 'ITADD', 'NIFTYBEES', 'MONIFTY100', 'MIDCAPETF', 'HDFCNIFIT', 'AXISNIFTY', 'ENIFTY', 'MONEXT50', 'AONENIFTY', 'MOM50', 'NEXT50IETF', 'MOM30IETF', 'NIFTYBETF', 'SMALLCAP', 'MIDCAP', 'NIFTYADD', 'IT', 'MOMENTUM', 'NIFTYIETF', 'HDFCMID150', 'NIFTYBETA', 'QNIFTY', 'NIFTYETF', 'GROWWNIFTY', 'SMALL250', 'NIFTY1', 'SETFNIF50', 'FLEXIADD', 'MIDSELIETF', 'MOALPHA50', 'HDFCVALUE', 'BSE500IETF', 'MOQUALITY', 'MOSERVICE', 'ALPHAETF', 'SNXT30BEES', 'SENSEXIETF', 'SBINEQWETF', 'AXISTECETF', 'EQUAL50', 'GROWWLOVOL', 'MIDCAPADD', 'SHARIABEES', 'GROWWRLTY', 'SMALLADD', 'AXSENSEX', 'LICNMID100', 'ESG', 'AONETOTAL', 'ESENSEX', 'SENSEXETF', 'MSCIADD', 'ALPL30IETF', 'NETF', 'MAKEINDIA', 'GROWWMOM50', 'BBETF0432', 'TNIDETF', 'BSLSENETFG', 'MOLOWVOL', 'SENSEXADD', 'MOMENTUM50', 'NEXT50BETA', 'GROWWCHEM', 'IDFNIFTYET', 'NPBET', 'NIFTYQLITY', 'NEXT50ETF', 'GILT10BETA', 'ABGSEC', 'LICNETFN50', 'SETFNN50', 'MNC', 'MOMNC', 'MAHKTECH', 'MIDQ50ADD', 'TOP20', 'NIF100IETF', 'EBBETF0433', 'SELECTIPO', 'LOWVOLIETF', 'PHARMABEES', 'NEXT50ADD', 'ALPHA', 'GROWWEV', 'HNGSNGBEES', 'LICNETFGSC', 'HDFCSENSEX', 'GILT5YBEES', 'TOP15IETF', 'HEALTHIETF', 'MOIPO', 'FMCGIETF', 'LOWVOL', 'LIQUID1', 'LIQUIDCASE', 'GROWWLIQID', 'ELIQUID', 'LIQUIDADD', 'HDFCLIQUID', 'LIQUIDBETF', 'SBILIQETF', 'LIQGRWBEES', 'CASHIETF', 'LIQUIDSHRI', 'LIQUIDPLUS', 'AONELIQUID', 'IVZINNIFTY', 'LIQUIDETF', 'LIQUIDSBI', 'ABSLLIQUID', 'LIQUIDIETF', 'LICNETFSEN', 'LIQUIDBEES', 'LIQUID', 'EBBETF0431', 'LTGILTCASE', 'MOGSEC', 'LTGILTBEES', 'EVINDIA', 'TECH', 'HDFCLOWVOL', 'EBBETF0430', 'GSEC10YEAR', 'GSEC10IETF', 'GROWWNXT50', 'GSEC10ABSL', 'HEALTHY', 'AXISBPSETF', 'SETF10GILT', 'CONSUMIETF', 'INTERNET', 'GSEC5IETF', 'CONSUMER', 'HEALTHADD', 'MON100', 'CONSUMBEES', 'DIVOPPBEES', 'HDFCGROWTH', 'SDL26BEES', 'GILT5BETA', 'VAL30IETF', 'MOMGF', 'AUTOBEES', 'HDFCBSE500', 'AUTOIETF', 'SBIETFCON', 'QUALITY30', 'AXISCETF', 'CONS', 'MASPTOP50', 'LOWVOL1', 'FINIETF', 'SNXT50BETA']

In [2]:
# When we have to update excel file
tickers = ['NIFTY 50', 'TATSILV', 'HDFCSILVER', 'SILVERAG', 'SILVERBETA', 'SBISILVER', 'AXISILVER', 'SILVERIETF', 'GROWWSLVR', 'SILVERCASE', 'SILVERBEES', 'SILVERADD', 'MOSILVER', 'SILVER', 'SILVER1', 'SILVERBND', 'ESILVER', 'SILVER360', 'HDFCMOMENT', 'EGOLD', 'GROWWN200', 'METALIETF', 'TWCGOLDETF', 'GOLDBND', 'GOLDETF', 'GROWWMETAL', 'CHOICEGOLD', 'TATAGOLD', 'HDFCPVTBAN', 'GROWWPOWER', 'GOLDIETF', 'GOLDBEES', 'IVZINGOLD', 'GROWWSC250', 'EVIETF', 'METAL', 'AXISGOLD', 'HDFCNEXT50', 'SETFGOLD', 'GOLDCASE', 'HDFCNIF100', 'GROWWNET', 'HDFCGOLD', 'HDFCQUAL', 'GOLD1', 'BSLGOLDETF', 'GOLDBETA', 'GROWWGOLD', 'QGOLDHALF', 'MOMENTUM30', 'GOLDADD', 'AONETMMQ50', 'AONEGOLD', 'GOLD360', 'MOGOLD', 'MODEFENCE', 'MOTOUR', 'AXISVALUE', 'GROWWDEFNC', 'PSUBNKBEES', 'COMMOIETF', 'BBNPPGOLD', 'HDFCPSUBK', 'SML100CASE', 'BANKPSU', 'SBIBPB', 'PSUBNKIETF', 'LICMFGOLD', 'PSUBANK', 'MANUFGBEES', 'MOVALUE', 'GROWWCAPM', 'BANKADD', 'CPSEETF', 'ELM250', 'BANKETF', 'ICICIB22', 'PSUBANKADD', 'MOCAPITAL', 'BANKIETF', 'HDFCNIFBAN', 'BBNPNBETF', 'TOP10ADD', 'BANKBETA', 'QUAL30IETF', 'DIVIDEND', 'BANKBEES', 'NIFTY100EW', 'BANKBETF', 'SETFNIFBK', 'MID150CASE', 'AXISBNKETF', 'ECAPINSURE', 'MOPSE', 'SBIETFIT', 'UNIONGOLD', 'NV20', 'NIF100BEES', 'PVTBANIETF', 'ITBEES', 'MOENERGY', 'BFSI', 'MONQ50', 'OILIETF', 'EMULTIMQ', 'ABSLPSE', 'BANKNIFTY1', 'SBIETFPB', 'ABSLBANETF', 'MONIFTY500', 'ITIETF', 'MOMOMENTUM', 'GROWWRAIL', 'MIDSMALL', 'NIFTYCASE', 'GROWWMC150', 'MID150', 'TOP100CASE', 'BSLNIFTY', 'PVTBANKADD', 'NEXT30ADD', 'AXISHCETF', 'ITETF', 'MOREALTY', 'MOMIDMTM', 'MAFANG', 'NEXT50', 'SBIETFQLTY', 'MOHEALTH', 'ENERGY', 'NV20BEES', 'MOM100', 'INFRABEES', 'MON50EQUAL', 'ABSLNN50ET', 'EQUAL200', 'MOINFRA', 'ITBETA', 'MIDCAPIETF', 'MULTICAP', 'MIDCAPBETA', 'JUNIORBEES', 'EQUAL50ADD', 'EBANKNIFTY', 'CHEMICAL', 'LICNFNHGP', 'MOSMALL250', 'HDFCSML250', 'SENSEXBETA', 'MID150BEES', 'HDFCNIFTY', 'MSCIINDIA', 'NV20IETF', 'INFRAIETF', 'ITADD', 'NIFTYBEES', 'MONIFTY100', 'MIDCAPETF', 'HDFCNIFIT', 'AXISNIFTY', 'ENIFTY', 'MONEXT50', 'AONENIFTY', 'MOM50', 'NEXT50IETF', 'MOM30IETF', 'NIFTYBETF', 'SMALLCAP', 'MIDCAP', 'NIFTYADD', 'IT', 'MOMENTUM', 'NIFTYIETF', 'HDFCMID150', 'NIFTYBETA', 'QNIFTY', 'NIFTYETF', 'GROWWNIFTY', 'SMALL250', 'NIFTY1', 'SETFNIF50', 'FLEXIADD', 'MIDSELIETF', 'MOALPHA50', 'HDFCVALUE', 'BSE500IETF', 'MOQUALITY', 'MOSERVICE', 'ALPHAETF', 'SNXT30BEES', 'SENSEXIETF', 'SBINEQWETF', 'AXISTECETF', 'EQUAL50', 'GROWWLOVOL', 'MIDCAPADD', 'SHARIABEES', 'GROWWRLTY', 'SMALLADD', 'AXSENSEX', 'LICNMID100', 'ESG', 'AONETOTAL', 'ESENSEX', 'SENSEXETF', 'MSCIADD', 'ALPL30IETF', 'NETF', 'MAKEINDIA', 'GROWWMOM50', 'BBETF0432', 'TNIDETF', 'BSLSENETFG', 'MOLOWVOL', 'SENSEXADD', 'MOMENTUM50', 'NEXT50BETA', 'GROWWCHEM', 'IDFNIFTYET', 'NPBET', 'NIFTYQLITY', 'NEXT50ETF', 'GILT10BETA', 'ABGSEC', 'LICNETFN50', 'SETFNN50', 'MNC', 'MOMNC', 'MAHKTECH', 'MIDQ50ADD', 'TOP20', 'NIF100IETF', 'EBBETF0433', 'SELECTIPO', 'LOWVOLIETF', 'PHARMABEES', 'NEXT50ADD', 'ALPHA', 'GROWWEV', 'HNGSNGBEES', 'LICNETFGSC', 'HDFCSENSEX', 'GILT5YBEES', 'TOP15IETF', 'HEALTHIETF', 'MOIPO', 'FMCGIETF', 'LOWVOL', 'LIQUID1', 'LIQUIDCASE', 'GROWWLIQID', 'ELIQUID', 'LIQUIDADD', 'HDFCLIQUID', 'LIQUIDBETF', 'SBILIQETF', 'LIQGRWBEES', 'CASHIETF', 'LIQUIDSHRI', 'LIQUIDPLUS', 'AONELIQUID', 'IVZINNIFTY', 'LIQUIDETF', 'LIQUIDSBI', 'ABSLLIQUID', 'LIQUIDIETF', 'LICNETFSEN', 'LIQUIDBEES', 'LIQUID', 'EBBETF0431', 'LTGILTCASE', 'MOGSEC', 'LTGILTBEES', 'EVINDIA', 'TECH', 'HDFCLOWVOL', 'EBBETF0430', 'GSEC10YEAR', 'GSEC10IETF', 'GROWWNXT50', 'GSEC10ABSL', 'HEALTHY', 'AXISBPSETF', 'SETF10GILT', 'CONSUMIETF', 'INTERNET', 'GSEC5IETF', 'CONSUMER', 'HEALTHADD', 'MON100', 'CONSUMBEES', 'DIVOPPBEES', 'HDFCGROWTH', 'SDL26BEES', 'GILT5BETA', 'VAL30IETF', 'MOMGF', 'AUTOBEES', 'HDFCBSE500', 'AUTOIETF', 'SBIETFCON', 'QUALITY30', 'AXISCETF', 'CONS', 'MASPTOP50', 'LOWVOL1', 'FINIETF', 'SNXT50BETA']

In [ ]:
enddate = date.today()
startdate = enddate - relativedelta(years=5)

In [ ]:
print(enddate)
print(startdate)

2026-01-30
2021-01-30

**Downloading NIFTY 50 data**

In [ ]:
nse_index = yf.download("^NSEI",start=startdate,end=enddate,auto_adjust=False,progress=False)

In [ ]:
nse_index.columns

MultiIndex([('Adj Close', '^NSEI'),
            (    'Close', '^NSEI'),
            (     'High', '^NSEI'),
            (      'Low', '^NSEI'),
            (     'Open', '^NSEI'),
            (   'Volume', '^NSEI')],
           names=['Price', 'Ticker'])

In [ ]:
nse_index.reset_index(inplace = True)
nse_index.columns = nse_index.columns.get_level_values(0)

In [ ]:
nse_index.head()

Price       Date     Adj Close  ...          Open  Volume
0     2021-01-27  13967.500000  ...  14237.950195  660700
1     2021-01-28  13817.549805  ...  13810.400391  637900
2     2021-01-29  13634.599609  ...  13946.599609  753200
3     2021-02-01  14281.200195  ...  13758.599609  870500
4     2021-02-02  14647.849609  ...  14481.099609  915000

[5 rows x 7 columns]

**Downloading all ETFs data**

In [ ]:
with pd.ExcelWriter("etf_data.xlsx", engine="openpyxl") as writer:
    for tick in tickers:
        print(f"Downloading {tick}.NS")

        df = yf.download(
            f"{tick}.NS",
            start=startdate,
            end=enddate,
            auto_adjust=False,
            progress=False
        )

        if df.empty:
            print(f"No data for {tick}")
            continue

        df.reset_index(inplace=True)
        df.columns = df.columns.get_level_values(0)
        df.to_excel(
            writer,
            sheet_name=tick,
            index=False
        )

IndexError: At least one sheet must be visible

In [ ]:
nse_index.to_excel("/content/nse_index_data.xlsx",index = False)

**Framework to append new data daily**

In [3]:
file_path = '/content/etf_data.xlsx'

In [3]:
def fetch_new_data(ticker, start_date):
  if ticker == "NIFTY 50":
    df = yf.download("^NSEI",start = start_date,progress = False)
  else:
    df = yf.download(
        f"{ticker}.NS",
        start=start_date,
        progress=False
    )

  if df.empty:
      return df

  df.reset_index(inplace=True)
  df.columns = df.columns.get_level_values(0)

  return df

In [4]:
def update_excel():
    file_exists = Path(file_path).exists()

    # Open writer in append mode
    with pd.ExcelWriter(
        file_path,
        engine="openpyxl",
        mode="a",
        if_sheet_exists="overlay"
    ) as writer:

        for ticker in tickers:
            print(f"Updating {ticker}")

            try:
                existing = pd.read_excel(file_path, sheet_name=ticker)
                last_date = pd.to_datetime(existing["Date"]).max()
                start_date = last_date + timedelta(days=1)
            except Exception:
                # Sheet doesn't exist
                existing = None
                start_date = last_date + timedelta(days=1)

            #Fetch new data
            new_data = fetch_new_data(ticker, start_date)

            if new_data.empty:
                print(f"No new data for {ticker}")
                continue

            #Combine & de-duplicate
            if existing is not None:
                combined = pd.concat([existing, new_data], ignore_index=True)
                combined.drop_duplicates(subset=["Date"], inplace=True)
            else:
                combined = new_data

            #Write back to same sheet
            combined.to_excel(
                writer,
                sheet_name=ticker,
                index=False
            )

    print("Excel update complete")

In [ ]:
update_excel()

Updating NIFTY 50

/tmp/ipython-input-2581299091.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download("^NSEI",start = start_date,progress = False)

Updating TATSILV

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCSILVER

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVERAG

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVERBETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SBISILVER

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISILVER

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVERIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWSLVR

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVERCASE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVERBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVERADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOSILVER

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVER

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVER1

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVERBND

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ESILVER

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SILVER360

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCMOMENT

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWN200

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating METALIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating TWCGOLDETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLDBND

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLDETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWMETAL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating CHOICEGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating TATAGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCPVTBAN

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWPOWER

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLDIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLDBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating IVZINGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWSC250

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EVIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating METAL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCNEXT50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SETFGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLDCASE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCNIF100

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWNET

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCQUAL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLD1

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BSLGOLDETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLDBETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating QGOLDHALF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOMENTUM30

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLDADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AONETMMQ50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AONEGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GOLD360

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MODEFENCE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOTOUR

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISVALUE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWDEFNC

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating PSUBNKBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating COMMOIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BBNPPGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCPSUBK

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SML100CASE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BANKPSU

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SBIBPB

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating PSUBNKIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LICMFGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating PSUBANK

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MANUFGBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOVALUE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWCAPM

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BANKADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating CPSEETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ELM250

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BANKETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ICICIB22

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating PSUBANKADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOCAPITAL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BANKIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCNIFBAN

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BBNPNBETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating TOP10ADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BANKBETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating QUAL30IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating DIVIDEND

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BANKBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTY100EW

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BANKBETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SETFNIFBK

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MID150CASE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISBNKETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ECAPINSURE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOPSE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SBIETFIT

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating UNIONGOLD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NV20

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIF100BEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating PVTBANIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ITBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOENERGY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BFSI

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MONQ50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating OILIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EMULTIMQ

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ABSLPSE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BANKNIFTY1

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SBIETFPB

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ABSLBANETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MONIFTY500

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ITIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOMOMENTUM

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWRAIL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MIDSMALL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTYCASE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWMC150

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MID150

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating TOP100CASE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BSLNIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating PVTBANKADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NEXT30ADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISHCETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ITETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOREALTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOMIDMTM

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MAFANG

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NEXT50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SBIETFQLTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOHEALTH

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ENERGY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NV20BEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOM100

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating INFRABEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MON50EQUAL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ABSLNN50ET

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EQUAL200

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOINFRA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ITBETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MIDCAPIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MULTICAP

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MIDCAPBETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating JUNIORBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EQUAL50ADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EBANKNIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating CHEMICAL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LICNFNHGP

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOSMALL250

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCSML250

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SENSEXBETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MID150BEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCNIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MSCIINDIA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NV20IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating INFRAIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ITADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTYBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MONIFTY100

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MIDCAPETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCNIFIT

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISNIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ENIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MONEXT50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AONENIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOM50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NEXT50IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOM30IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTYBETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SMALLCAP

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MIDCAP

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTYADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating IT

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOMENTUM

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTYIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCMID150

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTYBETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating QNIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTYETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWNIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SMALL250

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTY1

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SETFNIF50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating FLEXIADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MIDSELIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOALPHA50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCVALUE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BSE500IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOQUALITY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOSERVICE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ALPHAETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SNXT30BEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SENSEXIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SBINEQWETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISTECETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EQUAL50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWLOVOL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MIDCAPADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SHARIABEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWRLTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SMALLADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXSENSEX

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LICNMID100

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ESG

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AONETOTAL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ESENSEX

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SENSEXETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MSCIADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ALPL30IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MAKEINDIA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWMOM50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BBETF0432

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating TNIDETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating BSLSENETFG

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOLOWVOL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SENSEXADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOMENTUM50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NEXT50BETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWCHEM

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating IDFNIFTYET

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NPBET

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIFTYQLITY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NEXT50ETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GILT10BETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ABGSEC

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LICNETFN50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SETFNN50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MNC

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOMNC

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MAHKTECH

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MIDQ50ADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating TOP20

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NIF100IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EBBETF0433

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SELECTIPO

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LOWVOLIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating PHARMABEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating NEXT50ADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ALPHA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWEV

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HNGSNGBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LICNETFGSC

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCSENSEX

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GILT5YBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating TOP15IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HEALTHIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOIPO

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating FMCGIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LOWVOL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUID1

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDCASE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWLIQID

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ELIQUID

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCLIQUID

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDBETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SBILIQETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQGRWBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating CASHIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDSHRI

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDPLUS

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AONELIQUID

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating IVZINNIFTY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDSBI

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating ABSLLIQUID

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LICNETFSEN

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUIDBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LIQUID

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EBBETF0431

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LTGILTCASE

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOGSEC

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LTGILTBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EVINDIA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating TECH

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCLOWVOL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating EBBETF0430

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GSEC10YEAR

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GSEC10IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GROWWNXT50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GSEC10ABSL

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HEALTHY

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISBPSETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SETF10GILT

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating CONSUMIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating INTERNET

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GSEC5IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating CONSUMER

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HEALTHADD

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MON100

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating CONSUMBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating DIVOPPBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCGROWTH

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SDL26BEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating GILT5BETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating VAL30IETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MOMGF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AUTOBEES

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating HDFCBSE500

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AUTOIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SBIETFCON

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating QUALITY30

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating AXISCETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating CONS

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating MASPTOP50

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating LOWVOL1

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating FINIETF

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Updating SNXT50BETA

/tmp/ipython-input-2581299091.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(

Excel update complete

**ETFs Filtering**

In [ ]:
etf_metric = pd.DataFrame(index = tickers)
etf_metric = etf_metric.drop(index='NIFTY 50',axis=0)

In [ ]:
def universe_eligibility(
    data,
    as_of_date,
    atv_threshold=5e7,
    min_years=2
):

    # Ensure datetime
    data = data.copy()
    data['Date'] = pd.to_datetime(data['Date'])

    # Use only data up to as_of_date
    data = data[data['Date'] <= as_of_date]

    # Safeguard
    if data.empty:
        return False

    # Average Trading Value
    atv = (data['Close'] * data['Volume']).mean()

    # History requirement
    first_date = data['Date'].min()
    history_ok = (as_of_date - first_date) >= timedelta(days=365 * min_years)

    return (atv >= atv_threshold) and history_ok

In [ ]:
def portfolio_eligibility(
    data,
    as_of_date,
    ma_window=200,
    lookback_days=126
):
    """
    Portfolio eligibility as of a given date.
    """

    data = data.copy()
    data['Date'] = pd.to_datetime(data['Date'])

    # Use only data up to as_of_date
    data = data[data['Date'] <= as_of_date]

    # Not enough history
    if len(data) < max(ma_window, lookback_days):
        return False

    # Moving average
    data['200MA'] = data['Close'].rolling(window=ma_window).mean()

    latest_close = data.iloc[-1]['Close']
    latest_200ma = data.iloc[-1]['200MA']

    ma_condition = latest_close > latest_200ma

    # 6-month return
    past_price = data.iloc[-lookback_days]['Close']
    six_month_return = (latest_close / past_price) - 1

    return_condition = six_month_return > 0

    return ma_condition and return_condition

In [ ]:
def market_regime_flag(
    data,
    as_of_date,
    ma_window=200
):
    data = data.copy()
    data['Date'] = pd.to_datetime(data['Date'])

    # Use only data up to the evaluation date
    data = data[data['Date'] <= as_of_date]

    # Safeguard
    if len(data) < ma_window:
        return None  # or 'UNKNOWN'

    # Moving average
    data['MA'] = data['Close'].rolling(window=ma_window).mean()

    latest_close = data.iloc[-1]['Close']
    latest_ma = data.iloc[-1]['MA']

    return 'BEAR' if latest_close < latest_ma else 'BULL'

Scoring ETFs

In [ ]:
scoring = pd.DataFrame(index = etf_metric[etf_metric['Universe Eligibility']&etf_metric['Portfolio Eligibility']].index)
scoring

Empty DataFrame
Columns: []
Index: [TATSILV, SILVERBETA, SILVERIETF, SILVERBEES, SILVER, SILVER1, GOLDETF, TATAGOLD, GOLDIETF, GOLDBEES, SETFGOLD, HDFCGOLD, GOLD1, PSUBNKBEES, CPSEETF, ICICIB22, BANKBEES, SETFNIFBK, ITBEES, JUNIORBEES, NIFTYBEES, NIFTYIETF, NIFTYETF, SETFNIF50, LIQUID1, LIQUIDCASE, LIQUIDBEES, MON100]

In [ ]:
for ticker in scoring.index:

  data = pd.read_excel(file_path,sheet_name = ticker)

  data['daily_ret'] = data['Close'].pct_change()

  latest_close = data.iloc[-1]['Close']

    # RETURNS
  lookbacks = {
      '3M Return': 63,
      '6M Return': 126,
      '12M Return': 252
  }

  for name, days in lookbacks.items():
      past_price = data.iloc[-days]['Close']
      scoring.loc[ticker,name] = (latest_close / past_price) - 1

    # 3M VOLATILITY
  scoring.loc[ticker,'3M Volatility'] = (
      data['daily_ret'].iloc[-63:].std() * np.sqrt(252)
  )

In [ ]:
scoring

            3M Return  6M Return  12M Return  3M Volatility
TATSILV      1.130314   1.754054    2.408027       0.636415
SILVERBETA   1.019862   1.587100    2.203888       0.612030
SILVERIETF   1.002868   1.575744    2.187697       0.638423
SILVERBEES   1.047017   1.710056    2.255085       0.623683
SILVER       1.047003   1.716452    2.276281       0.656663
SILVER1      1.010299   1.588920    2.196992       0.618950
GOLDETF      0.324520   0.613507    0.957892       0.371818
TATAGOLD     0.346712   0.640999    0.983648       0.418950
GOLDIETF     0.358700   0.651135    1.000000       0.368523
GOLDBEES     0.313828   0.600000    0.932213       0.397478
SETFGOLD     0.326461   0.616497    0.949128       0.382050
HDFCGOLD     0.326389   0.612735    0.952149       0.390663
GOLD1        0.295283   0.579298    0.909478       0.376714
PSUBNKBEES   0.082257   0.327522    0.445291       0.186077
CPSEETF      0.054333   0.095137    0.194671       0.173512
ICICIB22     0.043508   0.121919    0.197895       0.129187
BANKBEES     0.030856   0.073205    0.221420       0.081735
SETFNIFBK    0.032835   0.073904    0.223314       0.079572
ITBEES       0.063118   0.084842   -0.106329       0.171500
JUNIORBEES  -0.032848   0.025886    0.098198       0.126076
NIFTYBEES   -0.009876   0.033820    0.105444       0.075308
NIFTYIETF   -0.019956   0.024120    0.110795       0.078422
NIFTYETF    -0.020535   0.026162    0.110264       0.078890
SETFNIF50   -0.009279   0.034405    0.106898       0.074194
LIQUID1      0.013054   0.026522    0.056022       0.001898
LIQUIDCASE   0.012687   0.026073    0.054925       0.002077
LIQUIDBEES   0.000000   0.000010    0.000000       0.000103
MON100      -0.044905   0.150384    0.114355       0.151649

In [ ]:
nifty_df = pd.read_excel(file_path, sheet_name="NIFTY 50")
nifty_df.columns = nifty_df.columns.str.lower()

nifty_6m_return = nifty_df['close'].pct_change(126).iloc[-1]
print(nifty_6m_return)

0.025920853367367824

In [ ]:
# Momentum Rank
scoring['Rank 6M']  = scoring['6M Return'].rank(ascending=False)
scoring['Rank 3M']  = scoring['3M Return'].rank(ascending=False)
scoring['Rank 12M'] = scoring['12M Return'].rank(ascending=False)

scoring['Momentum'] = (
    0.4 * scoring['Rank 6M'] +
    0.3 * scoring['Rank 3M'] +
    0.3 * scoring['Rank 12M']
)

scoring['Momentum Rank'] = scoring['Momentum'].rank(ascending = False)

# Relative Strength Rank
scoring['RS Raw'] = scoring['6M Return'] - nifty_6m_return

scoring['RS Rank'] = scoring['RS Raw'].rank(ascending=False)

# Risk Rank
scoring['Risk Rank'] = scoring['3M Volatility'].rank(ascending=True)

scoring.head()

,3M Return,6M Return,12M Return,3M Volatility,Rank 6M,Rank 3M,Rank 12M,Momentum,Momentum Rank,RS Raw,RS Rank,Risk Rank
TATSILV,1.130314,1.754054,2.408027,0.636415,1.0,1.0,1.0,1.0,1.0,1.728133,1.0,26.0
SILVERBETA,1.019862,1.587100,2.203888,0.612030,5.0,4.0,4.0,4.4,4.0,1.561179,5.0,23.0
SILVERIETF,1.002868,1.575744,2.187697,0.638423,6.0,6.0,6.0,6.0,6.0,1.549823,6.0,27.0
SILVERBEES,1.047017,1.710056,2.255085,0.623683,3.0,2.0,3.0,2.7,3.0,1.684135,3.0,25.0
SILVER,1.047003,1.716452,2.276281,0.656663,2.0,3.0,2.0,2.3,2.0,1.690531,2.0,28.0

In [ ]:
# Final Score
scoring['Final Score'] = (
    0.6  * scoring['Momentum Rank'] +
    0.25 * scoring['RS Rank'] +
    0.15 * scoring['Risk Rank']
)
scoring['Final Rank'] = scoring['Final Score'].rank()
scoring.head()

,3M Return,6M Return,12M Return,3M Volatility,Rank 6M,Rank 3M,Rank 12M,Momentum,Momentum Rank,RS Raw,RS Rank,Risk Rank,Final Score,Final Rank
TATSILV,1.130314,1.754054,2.408027,0.636415,1.0,1.0,1.0,1.0,1.0,1.728133,1.0,26.0,4.75,1.0
SILVERBETA,1.019862,1.587100,2.203888,0.612030,5.0,4.0,4.0,4.4,4.0,1.561179,5.0,23.0,7.10,4.0
SILVERIETF,1.002868,1.575744,2.187697,0.638423,6.0,6.0,6.0,6.0,6.0,1.549823,6.0,27.0,9.15,7.0
SILVERBEES,1.047017,1.710056,2.255085,0.623683,3.0,2.0,3.0,2.7,3.0,1.684135,3.0,25.0,6.30,3.0
SILVER,1.047003,1.716452,2.276281,0.656663,2.0,3.0,2.0,2.3,2.0,1.690531,2.0,28.0,5.90,2.0

In [ ]:
scoring['Final Rank'].rank()
scoring.sort_values(by = 'Final Rank')

,3M Return,6M Return,12M Return,3M Volatility,Rank 6M,Rank 3M,Rank 12M,Momentum,Momentum Rank,RS Raw,RS Rank,Risk Rank,Final Score,Final Rank
TATSILV,1.130314,1.754054,2.408027,0.636415,1.0,1.0,1.0,1.0,1.0,1.728133,1.0,26.0,4.75,1.0
SILVER,1.047003,1.716452,2.276281,0.656663,2.0,3.0,2.0,2.3,2.0,1.690531,2.0,28.0,5.90,2.0
SILVERBEES,1.047017,1.710056,2.255085,0.623683,3.0,2.0,3.0,2.7,3.0,1.684135,3.0,25.0,6.30,3.0
SILVERBETA,1.019862,1.587100,2.203888,0.612030,5.0,4.0,4.0,4.4,4.0,1.561179,5.0,23.0,7.10,4.0
SILVER1,1.010299,1.588920,2.196992,0.618950,4.0,5.0,5.0,4.6,5.0,1.562999,4.0,24.0,7.60,5.0
GOLDIETF,0.358700,0.651135,1.000000,0.368523,7.0,7.0,7.0,7.0,7.0,0.625214,7.0,16.0,8.35,6.0
SILVERIETF,1.002868,1.575744,2.187697,0.638423,6.0,6.0,6.0,6.0,6.0,1.549823,6.0,27.0,9.15,7.0
TATAGOLD,0.346712,0.640999,0.983648,0.418950,8.0,8.0,8.0,8.0,8.0,0.615078,8.0,22.0,10.10,8.0
SETFGOLD,0.326461,0.616497,0.949128,0.382050,9.0,9.0,11.0,9.6,9.0,0.590576,9.0,19.0,10.50,9.0
GOLDETF,0.324520,0.613507,0.957892,0.371818,10.0,11.0,9.0,10.0,10.0,0.587586,10.0,17.0,11.05,10.0
HDFCGOLD,0.326389,0.612735,0.952149,0.390663,11.0,10.0,10.0,10.4,11.0,0.586814,11.0,20.0,12.35,11.0
GOLDBEES,0.313828,0.600000,0.932213,0.397478,12.0,12.0,12.0,12.0,12.0,0.574079,12.0,21.0,13.35,12.0
GOLD1,0.295283,0.579298,0.909478,0.376714,13.0,13.0,13.0,13.0,13.0,0.553378,13.0,18.0,13.75,13.0
PSUBNKBEES,0.082257,0.327522,0.445291,0.186077,14.0,14.0,14.0,14.0,14.0,0.301602,14.0,15.0,14.15,14.0
ICICIB22,0.043508,0.121919,0.197895,0.129187,16.0,17.0,17.0,16.6,15.0,0.095999,16.0,11.0,14.65,15.0
CPSEETF,0.054333,0.095137,0.194671,0.173512,17.0,16.0,18.0,17.0,16.0,0.069216,17.0,14.0,15.95,16.0
SETFNIFBK,0.032835,0.073904,0.223314,0.079572,19.0,18.0,15.0,17.5,17.0,0.047983,19.0,8.0,16.15,17.0
BANKBEES,0.030856,0.073205,0.221420,0.081735,20.0,19.0,16.0,18.5,18.0,0.047284,20.0,9.0,17.15,18.0
MON100,-0.044905,0.150384,0.114355,0.151649,15.0,28.0,19.0,20.1,19.5,0.124463,15.0,12.0,17.25,19.0
ITBEES,0.063118,0.084842,-0.106329,0.171500,18.0,15.0,28.0,20.1,19.5,0.058921,18.0,13.0,18.15,20.0
SETFNIF50,-0.009279,0.034405,0.106898,0.074194,21.0,23.0,22.0,21.9,21.0,0.008484,21.0,4.0,18.45,21.0
LIQUID1,0.013054,0.026522,0.056022,0.001898,23.0,20.0,25.0,22.7,22.0,0.000601,23.0,2.0,19.25,22.0
NIFTYBEES,-0.009876,0.033820,0.105444,0.075308,22.0,24.0,23.0,22.9,23.0,0.007899,22.0,5.0,20.05,23.0
NIFTYETF,-0.020535,0.026162,0.110264,0.078890,24.0,26.0,21.0,23.7,24.0,0.000241,24.0,7.0,21.45,24.0
LIQUIDCASE,0.012687,0.026073,0.054925,0.002077,25.0,21.0,26.0,24.1,25.0,0.000153,25.0,3.0,21.70,25.0
NIFTYIETF,-0.019956,0.024120,0.110795,0.078422,27.0,25.0,20.0,24.3,26.0,-0.001801,27.0,6.0,23.25,26.0
LIQUIDBEES,0.000000,0.000010,0.000000,0.000103,28.0,22.0,27.0,25.9,28.0,-0.025911,28.0,1.0,23.95,27.0
JUNIORBEES,-0.032848,0.025886,0.098198,0.126076,26.0,27.0,24.0,25.7,27.0,-0.000035,26.0,10.0,24.20,28.0

**Backtesting**

In [4]:
# Read all sheets
xls = pd.ExcelFile(file_path)

etf_data = {}
for sheet in xls.sheet_names:
    df = pd.read_excel(xls, sheet_name=sheet)
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date')
    etf_data[sheet] = df

In [5]:
etf_data

{'NIFTY 50':            Date     Adj Close         Close          High           Low  \
 0    2021-01-27  13967.500000  13967.500000  14237.950195  13929.299805
 1    2021-01-28  13817.549805  13817.549805  13898.250000  13713.250000
 2    2021-01-29  13634.599609  13634.599609  13966.849609  13596.750000
 3    2021-02-01  14281.200195  14281.200195  14336.349609  13661.750000
 4    2021-02-02  14647.849609  14647.849609  14731.700195  14469.150391
 ...         ...           ...           ...           ...           ...
 1234 2026-01-23  25048.650391  25048.650391  25347.949219  25025.300781
 1235 2026-01-27           NaN  25175.400391  25246.650391  24932.550781
 1236 2026-01-28           NaN  25342.750000  25372.099609  25187.650391
 1237 2026-01-29           NaN  25418.900391  25458.150391  25159.800781
 1238 2026-01-30           NaN  25320.650391  25370.699219  25213.650391

               Open  Volume
 0     14237.950195  660700
 1     13810.400391  637900
 2     13946.599609  753200
 3     13758.599609  870500
 4     14481.099609  915000
 ...            ...     ...
 1234  25344.599609  393900
 1235  25063.349609  618700
 1236  25258.849609  574900
 1237  25345.000000  582400
 1238  25247.550781       0

 [1239 rows x 7 columns],
 'TATSILV':           Date  Adj Close      Close       High        Low       Open  \
 0   2024-01-17   8.080000   8.080000   8.400000   7.000000   7.000000
 1   2024-01-19   7.110000   7.110000   8.000000   7.050000   7.130000
 2   2024-01-23   7.020000   7.020000   7.190000   6.980000   7.100000
 3   2024-01-24   7.070000   7.070000   7.190000   7.000000   7.190000
 4   2024-01-25   7.100000   7.100000   7.180000   7.050000   7.080000
 ..         ...        ...        ...        ...        ...        ...
 494 2026-01-23  29.620001  29.620001  33.000000  29.100000  30.260000
 495 2026-01-27        NaN  32.520000  32.980000  31.000000  32.000000
 496 2026-01-28        NaN  33.220001  34.070000  32.930000  33.110001
 497 2026-01-29        NaN  34.939999  35.099998  34.009998  34.009998
 498 2026-01-30        NaN  30.570000  33.939999  29.900000  33.299999

         Volume
 0       680483
 1     31148770
 2       601696
 3       209744
 4       161560
 ..         ...
 494  688470900
 495  750857700
 496  639565500
 497  475472400
 498  883502587

 [499 rows x 7 columns],
 'HDFCSILVER':           Date   Adj Close       Close        High         Low        Open  \
 0   2024-03-26   72.779999   72.779999   73.800003   72.180000   73.800003
 1   2024-03-27   72.349998   72.349998   72.699997   72.099998   72.699997
 2   2024-03-28   72.419998   72.419998   72.839996   72.260002   72.680000
 3   2024-04-01   73.830002   73.830002   74.419998   72.820000   74.419998
 4   2024-04-02   74.570000   74.570000   74.690002   73.860001   73.900002
 ..         ...         ...         ...         ...         ...         ...
 449 2026-01-23  294.070007  294.070007  311.500000  287.649994  287.649994
 450 2026-01-27         NaN  322.649994  329.399994  308.450012  311.709991
 451 2026-01-28         NaN  335.899994  340.000000  324.200012  324.200012
 452 2026-01-29         NaN  355.420013  359.000000  344.000000  344.000000
 453 2026-01-30         NaN  297.239990  344.000000  285.000000  344.000000

        Volume
 0      238930
 1      149652
 2       72244
 3      380923
 4      380708
 ..        ...
 449  17624700
 450  23506500
 451  20542440
 452  16571270
 453  42494473

 [454 rows x 7 columns],
 'SILVERAG':           Date   Adj Close       Close        High         Low        Open  \
 0   2023-06-15   71.379997   71.379997   74.449997   71.209999   72.610001
 1   2023-06-16   72.209999   72.209999   77.830002   71.550003   74.970001
 2   2023-06-19   72.839996   72.839996   72.989998   71.010002   72.209999
 3   2023-06-20   72.199997   72.199997   72.750000   71.610001   72.610001
 4   2023-06-21   70.000000   70.000000   71.110001   69.550003   71.110001
 ..         ...         ...         ...         ...         ...         ...
 627 2026-01-23  298.059998  298.059998  312.380005  284.609985  284.609985
 628 2026-01-27         NaN  326.130005  330.000000  290.600006  290.600006
 629 2026-01-28         NaN  341.320007  348.700012  331.000000  348.700012
 630 2026-01-29         NaN  362.269989  380.000000  354.309998  380.000000
 631 2026-01-30         NaN  308.630005  360.950012  301.000000  360.950012

       Volume
 0       5139
 1       4669
 2       1980
 3       2024
 4      14838
 ..       ...
 627  1334977
 628  1939724
 629  1572185
 630  2243129
 631  3411705

 [632 rows x 7 columns],
 'SILVERBETA':           Date   Adj Close       Close        High         Low        Open  \
 0   2023-04-20   84.099998   84.099998   85.000000   76.400002   76.400002
 1   2023-04-21   83.000000   83.000000   83.000000   77.000000   81.199997
 2   2023-04-24   77.839996   77.839996   85.000000   77.000000   85.000000
 3   2023-04-25   79.790001   79.790001   80.699997   77.660004   79.389999
 4   2023-04-26   80.000000   80.000000   83.400002   78.989998   78.989998
 ..         ...         ...         ...         ...         ...         ...
 664 2026-01-23  296.769989  296.769989  311.869995  283.019989  283.019989
 665 2026-01-27         NaN  323.869995  327.989990  310.000000  310.000000
 666 2026-01-28         NaN  337.339996  341.000000  327.989990  327.989990
 667 2026-01-29         NaN  355.029999  379.660004  351.000000  359.899994
 668 2026-01-30         NaN  286.779999  355.029999  275.000000  355.029999

       Volume
 0        175
 1        603
 2       6952
 3       1654
 4       2914
 ..       ...
 664  3981842
 665  5280142
 666  4045431
 667  3947365
 668  8696243

 [669 rows x 7 columns],
 'SBISILVER':           Date   Adj Close       Close        High         Low        Open  \
 0   2024-07-08   91.550003   91.550003   91.699997   91.000000   91.550003
 1   2024-07-09   91.699997   91.699997   93.190002   90.099998   93.190002
 2   2024-07-10   92.000000   92.000000   93.010002   91.080002   91.699997
 3   2024-07-11   92.470001   92.470001   92.750000   91.629997   92.160004
 4   2024-07-12   92.260002   92.260002   93.279999   91.750000   92.470001
 ..         ...         ...         ...         ...         ...         ...
 382 2026-01-23  301.640015  301.640015  319.000000  294.000000  296.649994
 383 2026-01-27         NaN  327.190002  331.799988  310.549988  310.549988
 384 2026-01-28         NaN  341.049988  351.000000  329.000000  329.000000
 385 2026-01-29         NaN  358.239990  362.000000  346.299988  346.299988
 386 2026-01-30         NaN  284.809998  349.799988  277.989990  349.799988

        Volume
 0     2371286
 1     7780662
 2     1775642
 3      318887
 4      432006
 ..        ...
 382  10202830
 383  12875540
 384   9160568
 385  11110960
 386  18675116

 [387 rows x 7 columns],
 'AXISILVER':           Date   Adj Close       Close        High         Low        Open  \
 0   2022-09-21   60.000000   60.000000   60.000000   60.000000   60.000000
 1   2022-09-22   60.000000   60.000000   60.000000   60.000000   60.000000
 2   2022-09-23   60.000000   60.000000   60.000000   60.000000   60.000000
 3   2022-09-26   60.000000   60.000000   60.000000   60.000000   60.000000
 4   2022-09-27   54.759998   54.759998   57.459999   54.700001   57.459999
 ..         ...         ...         ...         ...         ...         ...
 828 2026-01-26  304.790009  304.790009  304.790009  304.790009  304.790009
 829 2026-01-27         NaN  330.809998  332.989990  297.170013  310.000000
 830 2026-01-28         NaN  347.730011  351.779999  336.000000  339.079987
 831 2026-01-29         NaN  371.470001  390.010010  363.380005  390.010010
 832 2026-01-30         NaN  296.600006  363.000000  283.000000  363.000000

       Volume
 0          0
 1          0
 2          0
 3          0
 4       1344
 ..       ...
 828        0
 829  3332707
 830  2768279
 831  2496493
 832  7170790

 [833 rows x 7 columns],
 'SILVERIETF':           Date   Adj Close       Close        High         Low        Open  \
 0   2022-01-31   63.279999   63.279999   66.599998   63.009998   66.599998
 1   2022-02-01   63.389999   63.389999   67.000000   62.910000   67.000000
 2   2022-02-02   63.790001   63.790001   63.950001   63.320000   63.400002
 3   2022-02-03   63.490002   63.490002   63.990002   63.250000   63.750000
 4   2022-02-04   63.240002   63.240002   66.400002   63.200001   63.889999
 ..         ...         ...         ...         ...         ...         ...
 963 2026-01-23  306.549988  306.549988  319.989990  301.299988  305.100006
 964 2026-01-27         NaN  332.940002  344.750000  321.200012  335.000000
 965 2026-01-28         NaN  348.029999  352.109985  324.609985  335.100006
 966 2026-01-29         NaN  367.250000  373.500000  355.109985  355.109985
 967 2026-01-30         NaN  293.299988  360.000000  284.119995  360.000000

        Volume
 0      383344
 1      373973
 2      240802
 3      456153
 4      482710
 ..        ...
 963  26472540
 964  38701570
 965  25287510
 966  25781280
 967  59927370

 [968 rows x 7 columns],
 'GROWWSLVR':           Date   Adj Close       Close        High         Low        Open  \
 0   2025-05-23   97.879997   97.879997   99.389999   94.199997   95.489998
 1   2025-05-26   97.610001   97.610001  100.000000   97.110001   98.980003
 2   2025-05-27   97.099998   97.099998   97.800003   96.910004   97.599998
 3   2025-05-28   97.730003   97.730003   98.120003   97.110001   97.110001
 4   2025-05-29   97.620003   97.620003   99.000000   97.000000   98.209999
 ..         ...         ...         ...         ...         ...         ...
 168 2026-01-23  301.109985  301.109985  314.940002  295.320007  295.320007
 169 2026-01-27         NaN  326.040009  329.989990  309.989990  310.000000
 170 2026-01-28         NaN  336.480011  345.149994  334.000000  334.200012
 171 2026-01-29         NaN  357.220001  362.989990  345.019989  345.019989
 172 2026-01-30         NaN  300.549988  347.390015  280.100006  347.220001

       Volume
 0    1344089
 1     141591
 2     120056
 3      27896
 4      15354
 ..       ...
 168  2239981
 169  3382103
 170  3759520
 171  2252872
 172  4744991

 [173 rows x 7 columns],
 'SILVERCASE':           Date  Adj Close      Close       High        Low       Open  \
 0   2025-03-26      10.17  10.170000  10.990000  10.100000  10.970000
 1   2025-03-27      10.18  10.180000  10.430000  10.160000  10.430000
 2   2025-03-28      10.37  10.370000  10.680000  10.300000  10.440000
 3   2025-04-01      10.26  10.260000  10.790000  10.200000  10.630000
 4   2025-04-02      10.25  10.250000  10.350000  10.180000  10.280000
 ..         ...        ...        ...        ...        ...        ...
 205 2026-01-23      31.23  31.230000  32.490002  30.610001  30.610001
 206 2026-01-27        NaN  33.889999  34.700001  32.000000  32.000000
 207 2026-01-28        NaN  35.730000  36.080002  34.290001  35.099998
 208 2026-01-29        NaN  37.799999  38.009998  37.000000  37.340000
 209 2026-01-30        NaN  31.480000  36.619999  30.000000  36.099998

         Volume
 0       156206
 1       132253
 2       319079
 3       631503
 4       220140
 ..         ...
 205   53931180
 206   89012270
 207   64515020
 208   67585480
 209  133035784

 [210 rows x 7 columns],
 'SILVERBEES':           Date   Adj Close       Close        High         Low        Open  \
 0   2022-02-04   60.959599   60.959599   60.959599   60.959599   60.959599
 1   2022-02-07   61.770000   61.770000   64.339996   59.439999   60.000000
 2   2022-02-08   62.279999   62.279999   63.000000   61.549999   62.000000
 3   2022-02-09   62.770000   62.770000   63.000000   62.009998   62.500000
 4   2022-02-10   62.799999   62.799999   64.900002   62.200001   63.000000
 ..         ...         ...         ...         ...         ...         ...
 983 2026-01-26  292.730011  292.730011  292.730011  292.730011  292.730011
 984 2026-01-27         NaN  317.850006  321.480011  305.700012  310.399994
 985 2026-01-28         NaN  332.029999  337.859985  320.799988  320.799988
 986 2026-01-29         NaN  351.910004  360.000000  346.149994  351.200012
 987 2026-01-30         NaN  286.480011  337.799988  276.660004  329.000000

         Volume
 0            0
 1       208834
 2        65666
 3       156227
 4       341078
 ..         ...
 983          0
 984  223275742
 985  170375606
 986  145645956
 987  391075491

 [988 rows x 7 columns],
 'SILVERADD':           Date   Adj Close       Close        High         Low        Open  \
 0   2024-02-07   69.110001   69.110001   69.360001   68.900002   69.360001
 1   2024-02-08   69.120003   69.120003   69.199997   68.750000   69.160004
 2   2024-02-09   69.989998   69.989998   70.000000   69.410004   70.000000
 3   2024-02-12   69.970001   69.970001   70.440002   69.699997   69.989998
 4   2024-02-13   69.980003   69.980003   70.379997   69.639999   70.379997
 ..         ...         ...         ...         ...         ...         ...
 482 2026-01-23  298.339996  298.339996  308.000000  276.420013  276.420013
 483 2026-01-27         NaN  323.190002  333.989990  290.880005  290.880005
 484 2026-01-28         NaN  339.000000  349.700012  330.029999  340.000000
 485 2026-01-29         NaN  351.920013  390.000000  348.640015  390.000000
 486 2026-01-30         NaN  283.369995  349.899994  274.290009  349.899994

       Volume
 0     312354
 1       9152
 2       1711
 3       4916
 4       3150
 ..       ...
 482  2557809
 483  1855301
 484  1367939
 485  3951594
 486  4935826

 [487 rows x 7 columns],
 'MOSILVER':           Date   Adj Close       Close        High         Low        Open  \
 0   2025-08-14  114.330002  114.330002  115.400002  114.330002  115.400002
 1   2025-08-18  114.050003  114.050003  114.620003  114.019997  114.620003
 2   2025-08-19  113.699997  113.699997  113.750000  113.699997  113.750000
 3   2025-08-20  113.190002  113.190002  116.540001  112.320000  116.540001
 4   2025-08-21  113.489998  113.489998  113.489998  113.489998  113.489998
 ..         ...         ...         ...         ...         ...         ...
 108 2026-01-23  307.540009  307.540009  315.000000  299.399994  304.399994
 109 2026-01-27         NaN  331.559998  335.000000  320.000000  322.660004
 110 2026-01-28         NaN  344.670013  351.899994  336.649994  336.649994
 111 2026-01-29         NaN  377.269989  385.000000  361.119995  362.000000
 112 2026-01-30         NaN  306.320007  376.750000  281.200012  376.750000

       Volume
 0      31136
 1        302
 2        313
 3       1719
 4       1049
 ..       ...
 108   971972
 109   333852
 110   326821
 111   550956
 112  1090523

 [113 rows x 7 columns],
 'SILVER':           Date   Adj Close       Close        High         Low        Open  \
 0   2022-01-31   63.110500   63.110500   63.110500   63.110500   63.110500
 1   2022-02-03   63.419998   63.419998   68.800003   63.200001   63.400002
 2   2022-02-04   63.450001   63.450001   65.000000   63.299999   63.500000
 3   2022-02-07   63.849998   63.849998   66.000000   63.450001   63.450001
 4   2022-02-08   63.869999   63.869999   65.150002   63.799999   65.150002
 ..         ...         ...         ...         ...         ...         ...
 985 2026-01-26  306.269989  306.269989  306.269989  306.269989  306.269989
 986 2026-01-27         NaN  333.059998  336.600006  314.989990  315.000000
 987 2026-01-28         NaN  349.200012  354.000000  340.010010  340.010010
 988 2026-01-29         NaN  367.119995  371.890015  359.899994  359.899994
 989 2026-01-30         NaN  299.190002  354.399994  284.100006  354.399994

        Volume
 0           0
 1           0
 2           0
 3           0
 4           0
 ..        ...
 985         0
 986  13896026
 987  11237917
 988  10647999
 989  26481312

 [990 rows x 7 columns],
 'SILVER1':           Date   Adj Close       Close        High         Low        Open  \
 0   2022-12-14   68.000000   68.000000   69.900002   66.500000   69.900002
 1   2022-12-15   66.699997   66.699997   67.500000   66.000000   67.500000
 2   2022-12-16   65.489998   65.489998   67.010002   65.209999   66.989998
 3   2022-12-19   66.269997   66.269997   66.989998   66.099998   66.099998
 4   2022-12-20   67.690002   67.690002   68.000000   65.199997   66.400002
 ..         ...         ...         ...         ...         ...         ...
 747 2026-01-23  302.320007  302.320007  309.989990  289.000000  291.010010
 748 2026-01-27         NaN  323.910004  334.750000  310.000000  310.000000
 749 2026-01-28         NaN  333.489990  340.149994  328.950012  334.750000
 750 2026-01-29         NaN  357.720001  388.000000  347.500000  350.000000
 751 2026-01-30         NaN  286.929993  350.000000  276.500000  344.989990

       Volume
 0       1642
 1       6911
 2      10874
 3      11931
 4      71127
 ..       ...
 747  4246819
 748  6006062
 749  5351500
 750  3573220
 751  9771717

 [752 rows x 7 columns],
 'SILVERBND':          Date   Adj Close       Close        High         Low        Open  \
 0  2025-12-12  191.820007  191.820007  198.000000  180.000000  180.100006
 1  2025-12-15  194.940002  194.940002  199.699997  188.669998  195.699997
 2  2025-12-16  194.880005  194.880005  198.990005  190.020004  195.000000
 3  2025-12-17  203.039993  203.039993  203.449997  194.979996  195.850006
 4  2025-12-18  202.300003  202.300003  206.940002  197.960007  197.960007
 5  2025-12-19  199.679993  199.679993  203.000000  195.649994  202.990005
 6  2025-12-22  214.889999  214.889999  217.800003  202.000000  204.669998
 7  2025-12-23  214.630005  214.630005  216.710007  209.210007  216.500000
 8  2025-12-24  219.610001  219.610001  223.440002  213.779999  215.699997
 9  2025-12-26  230.029999  230.029999  243.869995  222.000000  223.990005
 10 2025-12-29  257.079987  257.079987  261.420013  230.199997  235.789993
 11 2025-12-30  231.429993  231.429993  254.949997  225.250000  251.990005
 12 2025-12-31  229.399994  229.399994  237.000000  224.990005  233.199997
 13 2026-01-01  225.869995  225.869995  233.970001  225.100006  230.550003
 14 2026-01-02  240.050003  240.050003  245.289993  226.990005  227.600006
 15 2026-01-05  236.380005  236.380005  249.399994  233.440002  244.850006
 16 2026-01-06  241.720001  241.720001  242.350006  238.550003  239.000000
 17 2026-01-07  246.220001  246.220001  249.800003  242.000000  248.000000
 18 2026-01-08  234.770004  234.770004  248.210007  230.410004  248.210007
 19 2026-01-09  240.080002  240.080002  240.339996  235.210007  237.830002
 20 2026-01-12  251.929993  251.929993  254.009995  242.820007  254.000000
 21 2026-01-13  262.619995  262.619995  269.899994  252.550003  252.550003
 22 2026-01-14  276.019989  276.019989  279.000000  267.000000  274.399994
 23 2026-01-16  281.309998  281.309998  282.700012  269.309998  276.019989
 24 2026-01-19  318.029999  318.029999  330.929993  284.209991  284.209991
 25 2026-01-20  315.130005  315.130005  336.209991  304.010010  325.980011
 26 2026-01-21  320.850006  320.850006  333.000000  316.899994  323.010010
 27 2026-01-22  291.640015  291.640015  321.989990  251.160004  321.989990
 28 2026-01-23  311.679993  311.679993  319.579987  299.250000  299.250000
 29 2026-01-27         NaN  334.579987  343.690002  313.000000  313.000000
 30 2026-01-28         NaN  349.619995  354.000000  326.209991  326.209991
 31 2026-01-29         NaN  380.239990  389.000000  360.070007  360.079987
 32 2026-01-30         NaN  327.109985  374.000000  308.019989  374.000000

      Volume
 0     12488
 1     22077
 2      4753
 3     13421
 4      6677
 5      4877
 6     36087
 7     24190
 8     31103
 9     47902
 10   140016
 11   220402
 12    49592
 13    34170
 14    64618
 15   149481
 16    73526
 17    53954
 18    71920
 19    52648
 20   146939
 21   111523
 22   223764
 23   121138
 24   351858
 25  1114382
 26   201466
 27   342364
 28   129544
 29   510337
 30   365483
 31   326459
 32   796252  ,

In [6]:
EXPOSURE_MAP = {

    # ---- Broad Market ----
    "BROAD_MARKET": [
        "NIFTY", "NIFTY 50", "NIFTYBEES", "NIFTYETF", "NIFTYIETF",
        "SETFNIF50", "NIFTY1", "HDFCNIFTY", "AXISNIFTY",
        "SENSEX", "SENSEXIETF", "SENSEXETF", "AXSENSEX"
    ],

    # ---- Silver ETFs ----
    "SILVER": [
        "SILVER", "SILVERBEES", "SILVERETF", "SILVERADD",
        "TATSILV", "HDFCSILVER", "SBISILVER", "AXISILVER",
        "MOSILVER", "GROWWSLVR"
    ],

    # ---- Gold ETFs ----
    "GOLD": [
        "GOLD", "GOLDBEES", "GOLDETF", "HDFCGOLD", "AXISGOLD",
        "GROWWGOLD", "GOLDADD", "GOLD1"
    ],

    # ---- Banking & Financials ----
    "BANKING": [
        "BANKBEES", "BANKETF", "BANKNIFTY", "HDFCNIFBAN",
        "AXISBNKETF", "PSUBANK", "PSUBNKBEES", "FINIETF"
    ],

    # ---- IT ----
    "IT": [
        "ITBEES", "ITETF", "HDFCNIFIT", "ITADD"
    ],

    # ---- Mid / Small Cap ----
    "MID_SMALL": [
        "MIDCAP", "MIDCAPETF", "MID150", "MID150BEES",
        "SMALLCAP", "SMALL250"
    ],

    # ---- Factor ETFs ----
    "FACTOR": [
        "MOMENTUM", "LOWVOL", "QUALITY", "ALPHA",
        "NV20", "QUAL30IETF"
    ],

    # ---- Liquid / Debt ----
    "DEBT_LIQUID": [
        "LIQUID", "LIQUIDBEES", "LIQUIDETF",
        "GILT", "GSEC", "SDL"
    ],

    # ---- Thematic / Others ----
    "THEMATIC": [
        "DEFENCE", "PHARMA", "ENERGY", "AUTO", "INFRA"
    ]
}

In [7]:
def get_exposure(ticker):
    """
    Returns exposure bucket for a given ETF ticker
    """

    ticker = ticker.upper()

    for exposure, tickers in EXPOSURE_MAP.items():
        if any(ticker.startswith(t) for t in tickers):
            return exposure

    return "OTHER"

In [8]:
def build_exposure_dataframe(tickers):
    """
    Creates a dataframe mapping ETF -> exposure bucket
    """

    data = []

    for t in tickers:
        data.append({
            "Ticker": t,
            "Exposure": get_exposure(t)
        })

    return pd.DataFrame(data)

In [9]:
exposure_map = build_exposure_dataframe(tickers)

In [10]:
exposure_map

         Ticker      Exposure
0      NIFTY 50  BROAD_MARKET
1       TATSILV        SILVER
2    HDFCSILVER        SILVER
3      SILVERAG        SILVER
4    SILVERBETA        SILVER
..          ...           ...
303        CONS         OTHER
304   MASPTOP50         OTHER
305     LOWVOL1        FACTOR
306     FINIETF       BANKING
307  SNXT50BETA         OTHER

[308 rows x 2 columns]

In [11]:
# Costs associated

STT_RATE = 0.001
EXCHANGE_CHARGES = 0.0000345
SEBI_CHARGES = 0.0000001
STAMP = 0.00015
GST_RATE = 0.18

In [12]:
def transaction_cost(buy_turnover, sell_turnover):
    """
    Calculates total transaction cost for one portfolio rebalance
    (Indian ETFs – delivery).

    Parameters
    ----------
    buy_turnover : float
        Total value of BUY trades (₹)
    sell_turnover : float
        Total value of SELL trades (₹)

    Returns
    -------
    float
        Total transaction cost (₹)
    """

    total_turnover = buy_turnover + sell_turnover

    # ---- Charges ----
    stt = STT_RATE * total_turnover                 # STT on buy + sell
    exchange = EXCHANGE_CHARGES * total_turnover    # Exchange charges
    sebi = SEBI_CHARGES * total_turnover            # SEBI charges
    stamp = STAMP * buy_turnover                    # Stamp duty (buy-side only)

    gst = GST_RATE * (exchange + sebi)              # GST only on services

    total_cost = stt + exchange + sebi + stamp + gst

    return total_cost

In [13]:
def prepare_etf(df):
    df = df.copy()
    df['200MA'] = df['Close'].rolling(200).mean()
    df['3M_ret'] = df['Close'].pct_change(63)
    df['6M_ret'] = df['Close'].pct_change(126)
    df['12M_ret'] = df['Close'].pct_change(252)
    df['3M_vol'] = df['Close'].pct_change().rolling(63).std()
    return df

for k in etf_data:
    etf_data[k] = prepare_etf(etf_data[k])

In [14]:
etf_data

{'NIFTY 50':            Date     Adj Close         Close          High           Low  \
 0    2021-01-27  13967.500000  13967.500000  14237.950195  13929.299805
 1    2021-01-28  13817.549805  13817.549805  13898.250000  13713.250000
 2    2021-01-29  13634.599609  13634.599609  13966.849609  13596.750000
 3    2021-02-01  14281.200195  14281.200195  14336.349609  13661.750000
 4    2021-02-02  14647.849609  14647.849609  14731.700195  14469.150391
 ...         ...           ...           ...           ...           ...
 1234 2026-01-23  25048.650391  25048.650391  25347.949219  25025.300781
 1235 2026-01-27           NaN  25175.400391  25246.650391  24932.550781
 1236 2026-01-28           NaN  25342.750000  25372.099609  25187.650391
 1237 2026-01-29           NaN  25418.900391  25458.150391  25159.800781
 1238 2026-01-30           NaN  25320.650391  25370.699219  25213.650391

               Open  Volume         200MA    3M_ret    6M_ret   12M_ret  \
 0     14237.950195  660700           NaN       NaN       NaN       NaN
 1     13810.400391  637900           NaN       NaN       NaN       NaN
 2     13946.599609  753200           NaN       NaN       NaN       NaN
 3     13758.599609  870500           NaN       NaN       NaN       NaN
 4     14481.099609  915000           NaN       NaN       NaN       NaN
 ...            ...     ...           ...       ...       ...       ...
 1234  25344.599609  393900  25142.773818 -0.032549 -0.000489  0.079534
 1235  25063.349609  618700  25154.128574 -0.024026 -0.001764  0.078418
 1236  25258.849609  574900  25170.034326 -0.024004  0.011198  0.100679
 1237  25345.000000  582400  25184.449580 -0.019945  0.023429  0.097755
 1238  25247.550781       0  25199.057080 -0.028144  0.025921  0.091156

         3M_vol
 0          NaN
 1          NaN
 2          NaN
 3          NaN
 4          NaN
 ...        ...
 1234  0.005137
 1235  0.005168
 1236  0.005168
 1237  0.005185
 1238  0.005166

 [1239 rows x 12 columns],
 'TATSILV':           Date  Adj Close      Close       High        Low       Open  \
 0   2024-01-17   8.080000   8.080000   8.400000   7.000000   7.000000
 1   2024-01-19   7.110000   7.110000   8.000000   7.050000   7.130000
 2   2024-01-23   7.020000   7.020000   7.190000   6.980000   7.100000
 3   2024-01-24   7.070000   7.070000   7.190000   7.000000   7.190000
 4   2024-01-25   7.100000   7.100000   7.180000   7.050000   7.080000
 ..         ...        ...        ...        ...        ...        ...
 494 2026-01-23  29.620001  29.620001  33.000000  29.100000  30.260000
 495 2026-01-27        NaN  32.520000  32.980000  31.000000  32.000000
 496 2026-01-28        NaN  33.220001  34.070000  32.930000  33.110001
 497 2026-01-29        NaN  34.939999  35.099998  34.009998  34.009998
 498 2026-01-30        NaN  30.570000  33.939999  29.900000  33.299999

         Volume     200MA    3M_ret    6M_ret   12M_ret    3M_vol
 0       680483       NaN       NaN       NaN       NaN       NaN
 1     31148770       NaN       NaN       NaN       NaN       NaN
 2       601696       NaN       NaN       NaN       NaN       NaN
 3       209744       NaN       NaN       NaN       NaN       NaN
 4       161560       NaN       NaN       NaN       NaN       NaN
 ..         ...       ...       ...       ...       ...       ...
 494  688470900  13.74385  1.058374  1.649374  2.320628  0.035438
 495  750857700  13.86105  1.326180  1.867725  2.653933  0.036656
 496  639565500  13.98300  1.339437  1.960784  2.728395  0.036667
 497  475472400  14.11330  1.559707  2.116860  2.886541  0.036329
 498  883502587  14.22155  1.124392  1.766516  2.434832  0.040090

 [499 rows x 12 columns],
 'HDFCSILVER':           Date   Adj Close       Close        High         Low        Open  \
 0   2024-03-26   72.779999   72.779999   73.800003   72.180000   73.800003
 1   2024-03-27   72.349998   72.349998   72.699997   72.099998   72.699997
 2   2024-03-28   72.419998   72.419998   72.839996   72.260002   72.680000
 3   2024-04-01   73.830002   73.830002   74.419998   72.820000   74.419998
 4   2024-04-02   74.570000   74.570000   74.690002   73.860001   73.900002
 ..         ...         ...         ...         ...         ...         ...
 449 2026-01-23  294.070007  294.070007  311.500000  287.649994  287.649994
 450 2026-01-27         NaN  322.649994  329.399994  308.450012  311.709991
 451 2026-01-28         NaN  335.899994  340.000000  324.200012  324.200012
 452 2026-01-29         NaN  355.420013  359.000000  344.000000  344.000000
 453 2026-01-30         NaN  297.239990  344.000000  285.000000  344.000000

        Volume      200MA    3M_ret    6M_ret   12M_ret    3M_vol
 0      238930        NaN       NaN       NaN       NaN       NaN
 1      149652        NaN       NaN       NaN       NaN       NaN
 2       72244        NaN       NaN       NaN       NaN       NaN
 3      380923        NaN       NaN       NaN       NaN       NaN
 4      380708        NaN       NaN       NaN       NaN       NaN
 ..        ...        ...       ...       ...       ...       ...
 449  17624700  135.73975  1.085307  1.658380  2.300820  0.029721
 450  23506500  136.90250  1.322560  1.873876  2.665228  0.031383
 451  20542440  138.14645  1.418112  2.023402  2.817479  0.031515
 452  16571270  139.48400  1.659732  2.205158  3.037487  0.031252
 453  42494473  140.52780  1.098856  1.719985  2.348051  0.038141

 [454 rows x 12 columns],
 'SILVERAG':           Date   Adj Close       Close        High         Low        Open  \
 0   2023-06-15   71.379997   71.379997   74.449997   71.209999   72.610001
 1   2023-06-16   72.209999   72.209999   77.830002   71.550003   74.970001
 2   2023-06-19   72.839996   72.839996   72.989998   71.010002   72.209999
 3   2023-06-20   72.199997   72.199997   72.750000   71.610001   72.610001
 4   2023-06-21   70.000000   70.000000   71.110001   69.550003   71.110001
 ..         ...         ...         ...         ...         ...         ...
 627 2026-01-23  298.059998  298.059998  312.380005  284.609985  284.609985
 628 2026-01-27         NaN  326.130005  330.000000  290.600006  290.600006
 629 2026-01-28         NaN  341.320007  348.700012  331.000000  348.700012
 630 2026-01-29         NaN  362.269989  380.000000  354.309998  380.000000
 631 2026-01-30         NaN  308.630005  360.950012  301.000000  360.950012

       Volume      200MA    3M_ret    6M_ret   12M_ret    3M_vol
 0       5139        NaN       NaN       NaN       NaN       NaN
 1       4669        NaN       NaN       NaN       NaN       NaN
 2       1980        NaN       NaN       NaN       NaN       NaN
 3       2024        NaN       NaN       NaN       NaN       NaN
 4      14838        NaN       NaN       NaN       NaN       NaN
 ..       ...        ...       ...       ...       ...       ...
 627  1334977  137.49795  1.087986  1.651779  2.321743  0.031134
 628  1939724  138.67000  1.345415  1.859786  2.642283  0.032411
 629  1572185  139.93535  1.409431  2.025618  2.806401  0.032663
 630  2243129  141.30330  1.645465  2.214748  3.023434  0.032602
 631  3411705  142.39860  1.130393  1.782456  2.452237  0.038190

 [632 rows x 12 columns],
 'SILVERBETA':           Date   Adj Close       Close        High         Low        Open  \
 0   2023-04-20   84.099998   84.099998   85.000000   76.400002   76.400002
 1   2023-04-21   83.000000   83.000000   83.000000   77.000000   81.199997
 2   2023-04-24   77.839996   77.839996   85.000000   77.000000   85.000000
 3   2023-04-25   79.790001   79.790001   80.699997   77.660004   79.389999
 4   2023-04-26   80.000000   80.000000   83.400002   78.989998   78.989998
 ..         ...         ...         ...         ...         ...         ...
 664 2026-01-23  296.769989  296.769989  311.869995  283.019989  283.019989
 665 2026-01-27         NaN  323.869995  327.989990  310.000000  310.000000
 666 2026-01-28         NaN  337.339996  341.000000  327.989990  327.989990
 667 2026-01-29         NaN  355.029999  379.660004  351.000000  359.899994
 668 2026-01-30         NaN  286.779999  355.029999  275.000000  355.029999

       Volume      200MA    3M_ret    6M_ret   12M_ret    3M_vol
 0        175        NaN       NaN       NaN       NaN       NaN
 1        603        NaN       NaN       NaN       NaN       NaN
 2       6952        NaN       NaN       NaN       NaN       NaN
 3       1654        NaN       NaN       NaN       NaN       NaN
 4       2914        NaN       NaN       NaN       NaN       NaN
 ..       ...        ...       ...       ...       ...       ...
 664  3981842  136.75725  1.092139  1.662331  2.331874  0.027321
 665  5280142  137.92150  1.329832  1.854486  2.644312  0.028768
 666  4045431  139.16710  1.423768  2.006863  2.789060  0.028930
 667  3947365  140.49790  1.629852  2.166518  2.954004  0.028745
 668  8696243  141.48590  1.016312  1.599764  2.220438  0.038554

 [669 rows x 12 columns],
 'SBISILVER':           Date   Adj Close       Close        High         Low        Open  \
 0   2024-07-08   91.550003   91.550003   91.699997   91.000000   91.550003
 1   2024-07-09   91.699997   91.699997   93.190002   90.099998   93.190002
 2   2024-07-10   92.000000   92.000000   93.010002   91.080002   91.699997
 3   2024-07-11   92.470001   92.470001   92.750000   91.629997   92.160004
 4   2024-07-12   92.260002   92.260002   93.279999   91.750000   92.470001
 ..         ...         ...         ...         ...         ...         ...
 382 2026-01-23  301.640015  301.640015  319.000000  294.000000  296.649994
 383 2026-01-27         NaN  327.190002  331.799988  310.549988  310.549988
 384 2026-01-28         NaN  341.049988  351.000000  329.000000  329.000000
 385 2026-01-29         NaN  358.239990  362.000000  346.299988  346.299988
 386 2026-01-30         NaN  284.809998  349.799988  277.989990  349.799988

        Volume      200MA    3M_ret    6M_ret   12M_ret    3M_vol
 0     2371286        NaN       NaN       NaN       NaN       NaN
 1     7780662        NaN       NaN       NaN       NaN       NaN
 2     1775642        NaN       NaN       NaN       NaN       NaN
 3      318887        NaN       NaN       NaN       NaN       NaN
 4      432006        NaN       NaN       NaN       NaN       NaN
 ..        ...        ...       ...       ...       ...       ...
 382  10202830  138.53280  1.050299  1.671745  2.367270  0.029258
 383  12875540  139.70775  1.338073  1.849839  2.625374  0.029624
 384   9160568  140.96705  1.418108  2.001672  2.798307  0.029827
 385  11110960  142.30970  1.622932  2.153243  2.954084  0.029568
 386  18675116  143.28275  0.976612  1.544764  2.164204  0.040234

 [387 rows x 12 columns],
 'AXISILVER':           Date   Adj Close       Close        High         Low        Open  \
 0   2022-09-21   60.000000   60.000000   60.000000   60.000000   60.000000
 1   2022-09-22   60.000000   60.000000   60.000000   60.000000   60.000000
 2   2022-09-23   60.000000   60.000000   60.000000   60.000000   60.000000
 3   2022-09-26   60.000000   60.000000   60.000000   60.000000   60.000000
 4   2022-09-27   54.759998   54.759998   57.459999   54.700001   57.459999
 ..         ...         ...         ...         ...         ...         ...
 828 2026-01-26  304.790009  304.790009  304.790009  304.790009  304.790009
 829 2026-01-27         NaN  330.809998  332.989990  297.170013  310.000000
 830 2026-01-28         NaN  347.730011  351.779999  336.000000  339.079987
 831 2026-01-29         NaN  371.470001  390.010010  363.380005  390.010010
 832 2026-01-30         NaN  296.600006  363.000000  283.000000  363.000000

       Volume       200MA    3M_ret    6M_ret   12M_ret    3M_vol
 0          0         NaN       NaN       NaN       NaN       NaN
 1          0         NaN       NaN       NaN       NaN       NaN
 2          0         NaN       NaN       NaN       NaN       NaN
 3          0         NaN       NaN       NaN       NaN       NaN
 4       1344         NaN       NaN       NaN       NaN       NaN
 ..       ...         ...       ...       ...       ...       ...
 828        0  143.054211  1.084319  1.650117  2.317623  0.026971
 829  3332707  144.251361  1.257318  1.917453  2.623727  0.028473
 830  2768279  145.520961  1.347307  2.058849  2.783375  0.028864
 831  2496493  146.898911  1.508915  2.255653  3.087478  0.029596
 832  7170790  147.893911  1.037788  1.667506  2.287519  0.040099

 [833 rows x 12 columns],
 'SILVERIETF':           Date   Adj Close       Close        High         Low        Open  \
 0   2022-01-31   63.279999   63.279999   66.599998   63.009998   66.599998
 1   2022-02-01   63.389999   63.389999   67.000000   62.910000   67.000000
 2   2022-02-02   63.790001   63.790001   63.950001   63.320000   63.400002
 3   2022-02-03   63.490002   63.490002   63.990002   63.250000   63.750000
 4   2022-02-04   63.240002   63.240002   66.400002   63.200001   63.889999
 ..         ...         ...         ...         ...         ...         ...
 963 2026-01-23  306.549988  306.549988  319.989990  301.299988  305.100006
 964 2026-01-27         NaN  332.940002  344.750000  321.200012  335.000000
 965 2026-01-28         NaN  348.029999  352.109985  324.609985  335.100006
 966 2026-01-29         NaN  367.250000  373.500000  355.109985  355.109985
 967 2026-01-30         NaN  293.299988  360.000000  284.119995  360.000000

        Volume      200MA    3M_ret    6M_ret   12M_ret    3M_vol
 0      383344        NaN       NaN       NaN       NaN       NaN
 1      373973        NaN       NaN       NaN       NaN       NaN
 2      240802        NaN       NaN       NaN       NaN       NaN
 3      456153        NaN       NaN       NaN       NaN       NaN
 4      482710        NaN       NaN       NaN       NaN       NaN
 ..        ...        ...       ...       ...       ...       ...
 963  26472540  140.68940  1.061533  1.675890  2.370533  0.028888
 964  38701570  141.88715  1.302171  1.854913  2.652660  0.029914
 965  25287510  143.17330  1.405017  2.013769  2.813192  0.030126
 966  25781280  144.55600  1.632805  2.186828  2.988380  0.029850
 967  59927370  145.56410  1.002184  1.583230  2.211079  0.040217

 [968 rows x 12 columns],
 'GROWWSLVR':           Date   Adj Close       Close        High         Low        Open  \
 0   2025-05-23   97.879997   97.879997   99.389999   94.199997   95.489998
 1   2025-05-26   97.610001   97.610001  100.000000   97.110001   98.980003
 2   2025-05-27   97.099998   97.099998   97.800003   96.910004   97.599998
 3   2025-05-28   97.730003   97.730003   98.120003   97.110001   97.110001
 4   2025-05-29   97.620003   97.620003   99.000000   97.000000   98.209999
 ..         ...         ...         ...         ...         ...         ...
 168 2026-01-23  301.109985  301.109985  314.940002  295.320007  295.320007
 169 2026-01-27         NaN  326.040009  329.989990  309.989990  310.000000
 170 2026-01-28         NaN  336.480011  345.149994  334.000000  334.200012
 171 2026-01-29         NaN  357.220001  362.989990  345.019989  345.019989
 172 2026-01-30         NaN  300.549988  347.390015  280.100006  347.220001

       Volume  200MA    3M_ret    6M_ret  12M_ret    3M_vol
 0    1344089    NaN       NaN       NaN      NaN       NaN
 1     141591    NaN       NaN       NaN      NaN       NaN
 2     120056    NaN       NaN       NaN      NaN       NaN
 3      27896    NaN       NaN       NaN      NaN       NaN
 4      15354    NaN       NaN       NaN      NaN       NaN
 ..       ...    ...       ...       ...      ...       ...
 168  2239981    NaN  1.114833  1.648285      NaN  0.032568
 169  3382103    NaN  1.330355  1.827999      NaN  0.033518
 170  3759520    NaN  1.352514  1.949251      NaN  0.033579
 171  2252872    NaN  1.611257  2.139016      NaN  0.033274
 172  4744991    NaN  1.054481  1.677267      NaN  0.039230

 [173 rows x 12 columns],
 'SILVERCASE':           Date  Adj Close      Close       High        Low       Open  \
 0   2025-03-26      10.17  10.170000  10.990000  10.100000  10.970000
 1   2025-03-27      10.18  10.180000  10.430000  10.160000  10.430000
 2   2025-03-28      10.37  10.370000  10.680000  10.300000  10.440000
 3   2025-04-01      10.26  10.260000  10.790000  10.200000  10.630000
 4   2025-04-02      10.25  10.250000  10.350000  10.180000  10.280000
 ..         ...        ...        ...        ...        ...        ...
 205 2026-01-23      31.23  31.230000  32.490002  30.610001  30.610001
 206 2026-01-27        NaN  33.889999  34.700001  32.000000  32.000000
 207 2026-01-28        NaN  35.730000  36.080002  34.290001  35.099998
 208 2026-01-29        NaN  37.799999  38.009998  37.000000  37.340000
 209 2026-01-30        NaN  31.480000  36.619999  30.000000  36.099998

         Volume     200MA    3M_ret    6M_ret  12M_ret    3M_vol
 0       156206       NaN       NaN       NaN      NaN       NaN
 1       132253       NaN       NaN       NaN      NaN       NaN
 2       319079       NaN       NaN       NaN      NaN       NaN
 3       631503       NaN       NaN       NaN      NaN       NaN
 4       220140       NaN       NaN       NaN      NaN       NaN
 ..         ...       ...       ...       ...      ...       ...
 205   53931180  14.34245  1.091761  1.669231      NaN  0.028485
 206   89012270  14.46410  1.297627  1.850294      NaN  0.029756
 207   64515020  14.59650  1.432267  2.035684      NaN  0.030100
 208   67585480  14.73895  1.665726  2.217021      NaN  0.029912
 209  133035784  14.84950  1.108506  1.718480      NaN  0.037451

 [210 rows x 12 columns],
 'SILVERBEES':           Date   Adj Close       Close        High         Low        Open  \
 0   2022-02-04   60.959599   60.959599   60.959599   60.959599   60.959599
 1   2022-02-07   61.770000   61.770000   64.339996   59.439999   60.000000
 2   2022-02-08   62.279999   62.279999   63.000000   61.549999   62.000000
 3   2022-02-09   62.770000   62.770000   63.000000   62.009998   62.500000
 4   2022-02-10   62.799999   62.799999   64.900002   62.200001   63.000000
 ..         ...         ...         ...         ...         ...         ...
 983 2026-01-26  292.730011  292.730011  292.730011  292.730011  292.730011
 984 2026-01-27         NaN  317.850006  321.480011  305.700012  310.399994
 985 2026-01-28         NaN  332.029999  337.859985  320.799988  320.799988
 986 2026-01-29         NaN  351.910004  360.000000  346.149994  351.200012
 987 2026-01-30         NaN  286.480011  337.799988  276.660004  329.000000

         Volume      200MA    3M_ret    6M_ret   12M_ret    3M_vol
 0            0        NaN       NaN       NaN       NaN       NaN
 1       208834        NaN       NaN       NaN       NaN       NaN
 2        65666        NaN       NaN       NaN       NaN       NaN
 3       156227        NaN       NaN       NaN       NaN       NaN
 4       341078        NaN       NaN       NaN       NaN       NaN
 ..         ...        ...       ...       ...       ...       ...
 983          0  137.65970  1.074187  1.644832  2.303578  0.028119
 984  223275742  138.80910  1.261956  1.914718  2.618099  0.029530
 985  170375606  140.01740  1.330526  2.031684  2.744559  0.029790
 986  145645956  141.31585  1.470064  2.202676  3.017696  0.030288
 987  391075491  142.27925  1.047017  1.679888  2.289093  0.039288

 [988 rows x 12 columns],
 'SILVERADD':           Date   Adj Close       Close        High         Low        Open  \
 0   2024-02-07   69.110001   69.110001   69.360001   68.900002   69.360001
 1   2024-02-08   69.120003   69.120003   69.199997   68.750000   69.160004
 2   2024-02-09   69.989998   69.989998   70.000000   69.410004   70.000000
 3   2024-02-12   69.970001   69.970001   70.440002   69.699997   69.989998
 4   2024-02-13   69.980003   69.980003   70.379997   69.639999   70.379997
 ..         ...         ...         ...         ...         ...         ...
 482 2026-01-23  298.339996  298.339996  308.000000  276.420013  276.420013
 483 2026-01-27         NaN  323.190002  333.989990  290.880005  290.880005

In [15]:
def market_regime(nifty_df, as_of_date):
    df = nifty_df[nifty_df['Date'] <= as_of_date]
    if len(df) < 200:
        return None
    return 'BEAR' if df.iloc[-1]['Close'] < df.iloc[-1]['200MA'] else 'BULL'

In [16]:
def universe_eligible(df, as_of_date):
    df = df[df['Date'] <= as_of_date]
    if len(df) < 504:
        return False
    atv = (df['Close'] * df['Volume']).mean()
    return atv >= 5e7

def portfolio_eligible(df, as_of_date):
    df = df[df['Date'] <= as_of_date]
    if len(df) < 200:
        return False
    last = df.iloc[-1]
    return (last['Close'] > last['200MA']) and (last['6M_ret'] > 0)

In [17]:
start_date = pd.Timestamp("2021-01-01")
end_date = etf_data['NIFTY 50']['Date'].max()

rebalance_dates = pd.date_range(start_date, end_date, freq='M')

/tmp/ipython-input-3679190546.py:4: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  rebalance_dates = pd.date_range(start_date, end_date, freq='M')

In [18]:
rebalance_dates

DatetimeIndex(['2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31',
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31',
               '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [19]:
def score_etfs(etf_panel, nifty_6m_ret):
    df = etf_panel.copy()

    df['Momentum'] = (
        0.4 * df['6M_ret'].rank() +
        0.3 * df['3M_ret'].rank() +
        0.3 * df['12M_ret'].rank()
    )

    df['RS'] = (df['6M_ret'] - nifty_6m_ret).rank()
    df['Risk'] = df['3M_vol'].rank(ascending=False)

    df['FinalScore'] = (
        0.6 * df['Momentum'] +
        0.25 * df['RS'] +
        0.15 * df['Risk']
    )

    return df.sort_values('FinalScore', ascending=False)

In [20]:
def get_eligible_panel(etf_data, as_of_date):
    rows = []

    for ticker, df in etf_data.items():
        if ticker == 'NIFTY 50':
            continue

        if universe_eligible(df, as_of_date) and portfolio_eligible(df, as_of_date):
            row = df[df['Date'] <= as_of_date].iloc[-1]
            rows.append((ticker, row))

    if not rows:
        return None

    panel = pd.DataFrame({k: v for k, v in rows}).T
    return panel

In [21]:
def score_and_rank(panel, nifty_6m_ret):
    panel = panel.copy()

    panel['Momentum'] = (
        0.4 * panel['6M_ret'].rank(ascending=False) +
        0.3 * panel['3M_ret'].rank(ascending=False) +
        0.3 * panel['12M_ret'].rank(ascending=False)
    )

    panel['RS'] = (panel['6M_ret'] - nifty_6m_ret).rank(ascending=False)
    panel['Risk'] = panel['3M_vol'].rank()

    panel['FinalScore'] = (
        0.6 * panel['Momentum'] +
        0.25 * panel['RS'] +
        0.15 * panel['Risk']
    )

    return panel.sort_values('FinalScore', ascending=False)

In [82]:
PORTFOLIO_SIZE = 5
MAX_EXPOSURE = 0.35
MAX_TURNOVER = 0.40

In [102]:
def get_portfolio_size(regime, risk_profile):
    """
    Returns portfolio size based on market regime and risk aversion.
    """

    BULL_LIMITS = {
        'Conservative': 5,
        'Balanced': 8,
        'Aggressive': 10
    }

    BEAR_LIMITS = {
        'Conservative': 2,
        'Balanced': 3,
        'Aggressive': 5
    }

    base_sizes = {
        "BULL": BULL_LIMITS,
        "BEAR": BEAR_LIMITS
    }

    if regime not in base_sizes:
        raise ValueError("Invalid regime")

    if risk_profile not in BULL_LIMITS:
        raise ValueError("Invalid risk profile")

    size = base_sizes[regime][risk_profile]

    return size

In [58]:
# def build_portfolio(ranked_df, exposure_map):
#     selected = []
#     exposure_count = {}

#     max_per_exposure = int(PORTFOLIO_SIZE * MAX_EXPOSURE)

#     for etf in ranked_df.index:
#         exp = exposure_map.get(etf, 'Other')

#         if exposure_count.get(exp, 0) >= max_per_exposure:
#             continue

#         selected.append(etf)
#         if exp != 'Other':
#           exposure_count[exp] = exposure_count.get(exp, 0) + 1

#         if len(selected) == PORTFOLIO_SIZE:
#             break

#     weight = 1 / len(selected)  #can be altered
#     return {etf: weight for etf in selected}

In [107]:
def build_portfolio(ranked_df, exposure_map, regime, risk_profile):
    selected = []
    used_exposures = set()

    PORTFOLIO_SIZE = get_portfolio_size(regime,risk_profile)

    for etf in ranked_df.index:
        exp = exposure_map.get(etf, 'Other')

        # Skip if exposure already taken
        if exp in used_exposures:
            continue

        selected.append(etf)
        if exp != 'Other':
          used_exposures.add(exp)

        if len(selected) == PORTFOLIO_SIZE:
            break

    # weight = 1 / len(selected)
    # return {etf: weight for etf in selected}

    scores = ranked_df.loc[selected, 'FinalScore']

    # Ensure no negative weights (important if scores can be negative)
    scores = scores - scores.min()

    weights = scores / scores.sum()

    return weights.to_dict()

In [65]:
def capped_turnover(old_port, new_port, portfolio_value):
    buy, sell = 0, 0

    diffs = {}

    for etf in set(old_port) | set(new_port):
        old_w = old_port.get(etf, 0)
        new_w = new_port.get(etf, 0)
        diff = new_w - old_w

        if abs(diff) < 0.05:
            continue

        diffs[etf] = diff

        if diff > 0:
            buy += diff * portfolio_value
        else:
            sell += abs(diff) * portfolio_value

    total_turnover = buy + sell
    cap = MAX_TURNOVER * portfolio_value

    # No cap needed
    if total_turnover <= cap:
        return diffs, buy, sell

    # Scale trades proportionally
    scale = cap / total_turnover
    buy *= scale
    sell *= scale

    diffs = {k: v * scale for k, v in diffs.items()}

    return diffs, buy, sell

In [25]:
def portfolio_return(portfolio, etf_data, prev_date, curr_date):
    """
    Computes portfolio return between two rebalance dates.
    """
    ret = 0.0

    for etf, weight in portfolio.items():
        df = etf_data[etf]

        start = df[df['Date'] <= prev_date].iloc[-1]['Close']
        end = df[df['Date'] <= curr_date].iloc[-1]['Close']

        etf_ret = (end / start) - 1
        ret += weight * etf_ret

    return ret

In [108]:
portfolio = {}
portfolio_value = 1_000_000
history = []
risk_profile = 'Aggressive' #can choose from Conservative, Moderate, Aggressive

prev_date = None
nifty_df = etf_data['NIFTY 50']

for dt in rebalance_dates:

    # ---- APPLY RETURNS (holding period) ----
    if prev_date is not None and portfolio:
        ret = portfolio_return(portfolio, etf_data, prev_date, dt)
        portfolio_value *= (1 + ret)

    # ---- MARKET REGIME ----
    regime = market_regime(nifty_df, dt)
    if regime is None:
        prev_date = dt
        continue

    # ---- ELIGIBLE ETFs ----
    panel = get_eligible_panel(etf_data, dt)
    if panel is None:
        prev_date = dt
        continue

    nifty_6m = nifty_df[nifty_df['Date'] <= dt].iloc[-1]['6M_ret']
    ranked = score_and_rank(panel, nifty_6m)

    # ---- TARGET PORTFOLIO ----
    new_port = build_portfolio(ranked, exposure_map, market_regime(nifty_df,dt),risk_profile)

    # ---- TURNOVER + COST ----
    diffs, buy, sell = capped_turnover(
        portfolio, new_port, portfolio_value
    )

    num_of_trades = len(diffs)
    cost = transaction_cost(buy, sell)
    portfolio_value -= cost

    # ---- UPDATE HOLDINGS ----
    portfolio = new_port
    history.append((dt, portfolio_value, num_of_trades))
    # print(ranked)
    print(portfolio)

    prev_date = dt

{'SETFNIFBK': 0.34285714285714297, 'BANKBEES': 0.30238095238095236, 'ITBEES': 0.22142857142857145, 'CPSEETF': 0.1333333333333333, 'PSUBNKBEES': 0.0}
{'BANKBEES': 0.3802281368821294, 'SETFNIFBK': 0.3447401774397972, 'MON100': 0.1673003802281369, 'CPSEETF': 0.10773130544993666, 'PSUBNKBEES': 0.0}
{'SETFNIF50': 0.27345309381237526, 'NIFTYBEES': 0.2268795741849634, 'BANKBEES': 0.17232202262142388, 'SETFNIFBK': 0.1297405189620758, 'MON100': 0.10844976713240187, 'CPSEETF': 0.06719893546240852, 'PSUBNKBEES': 0.020625415834996674, 'GOLDBEES': 0.0013306719893546545, 'SETFGOLD': 0.0}
{'ITBEES': 0.3487819370172311, 'SETFNIF50': 0.1948900772430184, 'NIFTYBEES': 0.1532976827094474, 'GOLDBEES': 0.11348781937017231, 'BANKBEES': 0.0867498514557338, 'SETFGOLD': 0.04337492572786687, 'CPSEETF': 0.0409982174688057, 'SETFNIFBK': 0.01841948900772433, 'MON100': 0.0}
{'ITBEES': 0.25923076923076926, 'SETFGOLD': 0.15461538461538463, 'GOLDBEES': 0.15384615384615385, 'SETFNIFBK': 0.12961538461538463, 'JUNIORBEES': 0.11192307692307693, 'BANKBEES': 0.09769230769230769, 'SETFNIF50': 0.05961538461538463, 'NIFTYBEES': 0.03269230769230768, 'MON100': 0.00076923076923077, 'CPSEETF': 0.0}
{'ITBEES': 0.20159313725490197, 'SETFGOLD': 0.1994485294117647, 'GOLDBEES': 0.17800245098039216, 'SETFNIFBK': 0.125, 'BANKBEES': 0.10355392156862744, 'JUNIORBEES': 0.07567401960784313, 'SETFNIF50': 0.061580882352941166, 'NIFTYBEES': 0.030943627450980386, 'PSUBNKBEES': 0.02420343137254902, 'CPSEETF': 0.0}
{'ITBEES': 0.21294117647058824, 'GOLDBEES': 0.17607843137254905, 'SETFNIFBK': 0.16039215686274513, 'BANKBEES': 0.13294117647058826, 'SETFNIF50': 0.11607843137254902, 'JUNIORBEES': 0.10235294117647063, 'NIFTYBEES': 0.09098039215686271, 'CPSEETF': 0.004313725490196057, 'PSUBNKBEES': 0.003921568627450967, 'MON100': 0.0}
{'LIQUIDETF': 0.1845454545454545, 'LIQUIDBEES': 0.16333333333333339, 'SETFNIFBK': 0.14727272727272725, 'BANKBEES': 0.136969696969697, 'ITBEES': 0.12484848484848485, 'NIFTYBEES': 0.07575757575757576, 'MON100': 0.057878787878787884, 'JUNIORBEES': 0.054848484848484834, 'SETFNIF50': 0.05454545454545454, 'CPSEETF': 0.0}
{'SETFNIF50': 0.18772563176895307, 'SETFGOLD': 0.15724027276373848, 'NIFTYBEES': 0.14761331728840754, 'GOLDBEES': 0.13156839149618937, 'JUNIORBEES': 0.1275571600481348, 'ITBEES': 0.12434817488969116, 'MON100': 0.09827517047733655, 'PSUBNKBEES': 0.02567188126754916, 'CPSEETF': 0.0}
{'LIQUIDBEES': 0.2105820105820106, 'SETFNIFBK': 0.20070546737213407, 'BANKBEES': 0.17813051146384476, 'NIFTYBEES': 0.10758377425044093, 'GOLDBEES': 0.09206349206349206, 'SETFNIF50': 0.08500881834215165, 'MON100': 0.047619047619047616, 'ITBEES': 0.03950617283950616, 'JUNIORBEES': 0.03880070546737213, 'PSUBNKBEES': 0.0}
{'LIQUIDBEES': 0.21326164874551973, 'SETFGOLD': 0.17956989247311825, 'GOLDBEES': 0.1673835125448029, 'SETFNIFBK': 0.16057347670250902, 'BANKBEES': 0.1376344086021505, 'ITBEES': 0.06200716845878141, 'MON100': 0.04587813620071686, 'SETFNIF50': 0.02831541218637996, 'NIFTYBEES': 0.005376344086021519, 'PSUBNKBEES': 0.0}
{'LIQUIDETF': 0.19143356643356643, 'SETFNIFBK': 0.18589743589743593, 'BANKBEES': 0.16724941724941725, 'GOLDBEES': 0.1220862470862471, 'SETFGOLD': 0.1215034965034965, 'NIFTYBEES': 0.07546620046620046, 'SETFNIF50': 0.06555944055944056, 'ITBEES': 0.04662004662004661, 'MON100': 0.024184149184149187, 'JUNIORBEES': 0.0}
{'SETFNIFBK': 0.20090909090909093, 'BANKBEES': 0.19242424242424241, 'GOLDBEES': 0.16575757575757577, 'SETFNIF50': 0.11242424242424241, 'NIFTYBEES': 0.11181818181818182, 'ITBEES': 0.07818181818181817, 'MON100': 0.07484848484848486, 'JUNIORBEES': 0.03333333333333333, 'PSUBNKBEES': 0.030303030303030318, 'CPSEETF': 0.0}
{'SILVERBEES': 0.21739130434782608, 'ITBEES': 0.1766304347826087, 'BANKBEES': 0.1717995169082126, 'SETFNIFBK': 0.1506642512077295, 'GOLDBEES': 0.09842995169082128, 'NIFTYBEES': 0.0718599033816425, 'SETFNIF50': 0.061594202898550714, 'MON100': 0.02958937198067633, 'JUNIORBEES': 0.022041062801932368, 'PSUBNKBEES': 0.0}
{'SILVERBEES': 0.20868744098205855, 'SETFNIFBK': 0.18004406672961917, 'BANKBEES': 0.14856783128737805, 'SETFNIF50': 0.10827824992130944, 'NIFTYBEES': 0.10764872521246463, 'GOLDBEES': 0.09946490399748192, 'MON100': 0.07522820270695628, 'SETFGOLD': 0.0538243626062323, 'JUNIORBEES': 0.01825621655649985, 'PSUBNKBEES': 0.0}
{'LIQUIDETF': 0.2000328731097962, 'LIQUIDBEES': 0.1951019066403682, 'SETFNIFBK': 0.1482577251808021, 'BANKBEES': 0.12721893491124264, 'SETFNIF50': 0.10618014464168311, 'NIFTYBEES': 0.08514135437212363, 'MON100': 0.06508875739644969, 'GOLDBEES': 0.0529257067718606, 'SETFGOLD': 0.02005259697567391, 'SILVERBEES': 0.0}
{'ITBEES': 0.21189311253293194, 'SETFNIFBK': 0.17199849454271737, 'BANKBEES': 0.13887843432442604, 'GOLDBEES': 0.13436206247647725, 'SETFNIF50': 0.09108016560030106, 'SETFGOLD': 0.08543470079036504, 'NIFTYBEES': 0.06925103500188183, 'SILVERBEES': 0.05796010538200976, 'PSUBNKBEES': 0.0391418893488897, 'MON100': 0.0}
{'SETFGOLD': 0.18579960185799607, 'GOLDBEES': 0.1745189117451891, 'MON100': 0.1363636363636364, 'SILVERBEES': 0.1340411413404114, 'BANKBEES': 0.1287325812873258, 'SETFNIFBK': 0.10749834107498339, 'ITBEES': 0.07730590577305906, 'PSUBNKBEES': 0.04246848042468478, 'NIFTYBEES': 0.013271400132714013, 'SETFNIF50': 0.0}
{'LIQUIDBEES': 0.21530080530554233, 'LIQUIDETF': 0.2138796778777831, 'BANKBEES': 0.20037896731406912, 'SETFNIFBK': 0.15300805305542403, 'MON100': 0.10563713879677876, 'GOLDBEES': 0.06300331596399814, 'SILVERBEES': 0.038370440549502616, 'SETFNIF50': 0.00805305542396976, 'SETFGOLD': 0.002368545712932335, 'NIFTYBEES': 0.0}
{'MON100': 0.20339525944907108, 'GOLDBEES': 0.16367713004484302, 'BANKBEES': 0.16303651505445227, 'SETFGOLD': 0.14317745035233825, 'SETFNIFBK': 0.13100576553491353, 'SILVERBEES': 0.0842408712363869, 'NIFTYBEES': 0.047085201793721984, 'ITBEES': 0.037796284433055743, 'SETFNIF50': 0.026585522101217195, 'ICICIB22': 0.0}
{'SETFNIFBK': 0.1782467532467533, 'BANKBEES': 0.17759740259740261, 'ICICIB22': 0.15357142857142858, 'CPSEETF': 0.14155844155844158, 'NIFTYBEES': 0.1107142857142857, 'JUNIORBEES': 0.10519480519480522, 'SETFNIF50': 0.07824675324675323, 'MID150BEES': 0.03246753246753247, 'SETFGOLD': 0.02240259740259739, 'MON100': 0.0}
{'ICICIB22': 0.1922222222222222, 'JUNIORBEES': 0.1796296296296296, 'SETFNIF50': 0.11407407407407409, 'SETFGOLD': 0.10814814814814813, 'GOLDBEES': 0.09555555555555555, 'NIFTYBEES': 0.08814814814814813, 'MID150BEES': 0.0844444444444444, 'SETFNIFBK': 0.06925925925925924, 'BANKBEES': 0.06851851851851852, 'MON100': 0.0}
{'LIQUIDBEES': 0.3742857142857144, 'MID150BEES': 0.31714285714285706, 'SETFGOLD': 0.17857142857142855, 'GOLDBEES': 0.13000000000000006, 'ITBEES': 0.0}
{'ITBEES': 0.4171428571428572, 'SILVERBEES': 0.3685714285714285, 'SETFGOLD': 0.13142857142857142, 'GOLDBEES': 0.08285714285714281, 'MON100': 0.0}
{'MON100': 0.4183333333333334, 'SILVERBEES': 0.41500000000000004, 'GOLDBEES': 0.16666666666666666, 'SETFGOLD': 0.0}
{'LIQUIDBEES': 0.3688760806916427, 'MON100': 0.33573487031700283, 'SILVERBEES': 0.20749279538904902, 'SILVERIETF': 0.0878962536023055, 'GOLDBEES': 0.0}
{'BANKBEES': 0.5948275862068966, 'SETFNIFBK': 0.3074712643678161, 'SETFGOLD': 0.09770114942528739, 'GOLDBEES': 0.0}
{'CPSEETF': 0.19496855345911954, 'NIFTYBEES': 0.14919636617749826, 'MID150BEES': 0.1443046820405311, 'PSUBNKBEES': 0.13172606568832984, 'SETFNIF50': 0.1142557651991614, 'SILVERBEES': 0.10866526904262754, 'SILVERIETF': 0.096785464709993, 'BANKBEES': 0.05276030747728863, 'SETFNIFBK': 0.007337526205450732, 'GOLDBEES': 0.0}
{'ICICIB22': 0.21167883211678837, 'HDFCSML250': 0.1605839416058394, 'LIQUID1': 0.15985401459854012, 'PSUBNKBEES': 0.10693430656934308, 'MID150BEES': 0.095985401459854, 'NIFTYBEES': 0.09562043795620438, 'CPSEETF': 0.08248175182481754, 'SETFNIF50': 0.05693430656934308, 'SILVERBEES': 0.02992700729927008, 'SILVERIETF': 0.0}
{'ICICIB22': 0.1990756025090789, 'LIQUID1': 0.15912842522284584, 'NIFTYBEES': 0.1323869263783427, 'PSUBNKBEES': 0.11786068009243977, 'SETFNIF50': 0.114229118520964, 'JUNIORBEES': 0.0947507428194124, 'CPSEETF': 0.09243974909210959, 'MON100': 0.06965995378012539, 'HDFCSML250': 0.020468801584681447, 'MID150BEES': 0.0}
{'JUNIORBEES': 0.25597749648382573, 'MON100': 0.2320675105485231, 'NIFTYBEES': 0.13642756680731363, 'SETFNIF50': 0.08860759493670892, 'PSUBNKBEES': 0.08860759493670892, 'HDFCSML250': 0.06469760900140654, 'LIQUID1': 0.057665260196905745, 'BANKBEES': 0.04781997187060473, 'MID150BEES': 0.028129395218002694, 'SETFNIFBK': 0.0}
{'NIFTYETF': 0.19099099099099104, 'LIQUIDBEES': 0.14189189189189183, 'NIFTYBEES': 0.13603603603603603, 'SETFNIF50': 0.12162162162162161, 'CPSEETF': 0.11711711711711706, 'LIQUIDETF': 0.11216216216216213, 'ICICIB22': 0.09909909909909911, 'HDFCSML250': 0.06666666666666661, 'JUNIORBEES': 0.01441441441441457, 'MID150BEES': 0.0}
{'PHARMABEES': 0.2875104777870913, 'LIQUID1': 0.17854149203688177, 'SETFNIFBK': 0.12740989103101422, 'CPSEETF': 0.12657166806370493, 'BANKBEES': 0.09681475272422468, 'HDFCSML250': 0.06077116512992464, 'JUNIORBEES': 0.05071248952221292, 'NIFTYETF': 0.041911148365465264, 'MID150BEES': 0.029756915339480394, 'NIFTYBEES': 0.0}
{'HDFCSML250': 0.2337106148669317, 'ITBEES': 0.2113796267971857, 'JUNIORBEES': 0.1538696849189355, 'LIQUID1': 0.13031508106454567, 'MID150BEES': 0.09299479963291525, 'ICICIB22': 0.06423982869379015, 'PHARMABEES': 0.05200367084735391, 'SETFNIF50': 0.04190884062404408, 'NIFTYETF': 0.019577852554297916, 'NIFTYBEES': 0.0}
{'JUNIORBEES': 0.2486559139784949, 'LIQUIDETF': 0.24238351254480278, 'MID150BEES': 0.20116487455197146, 'LIQUID1': 0.15098566308243733, 'PHARMABEES': 0.07213261648745514, 'SETFNIF50': 0.0389784946236559, 'NIFTYETF': 0.030465949820788457, 'MON100': 0.013440860215053644, 'NIFTYBEES': 0.0017921146953404647, 'NIFTYIETF': 0.0}

In [109]:
result = pd.DataFrame(history, columns=['Date', 'Portfolio','No. of Trades'])
result = result.set_index('Date')

nifty_df = pd.read_excel(file_path, sheet_name="NIFTY 50")
nifty_df["Date"] = pd.to_datetime(nifty_df["Date"])

nifty_curve = nifty_df.set_index("Date")["Close"]

# Align NIFTY to portfolio dates safely
nifty_curve = nifty_curve.reindex(
    result.index,
    method="ffill"
)

# Normalize to same starting value
nifty_curve = nifty_curve / nifty_curve.iloc[0] * result.iloc[0, 0]

comparison = pd.concat([result, nifty_curve.rename('NIFTY')], axis=1)

In [79]:
assert nifty_curve.isna().sum() == 0

In [110]:
comparison

               Portfolio  No. of Trades         NIFTY
Date
2023-02-28  9.995237e+05              4  9.995237e+05
2023-03-31  9.962765e+05              3  1.002747e+06
2023-04-30  1.046501e+06              5  1.043484e+06
2023-05-31  1.083794e+06              7  1.070598e+06
2023-06-30  1.097827e+06              6  1.108412e+06
2023-07-31  1.121167e+06              1  1.141034e+06
2023-08-31  1.118431e+06              3  1.112152e+06
2023-09-30  1.130933e+06              6  1.134362e+06
2023-10-31  1.105609e+06              9  1.102090e+06
2023-11-30  1.166831e+06              8  1.162946e+06
2023-12-31  1.234516e+06              4  1.255265e+06
2024-01-31  1.218998e+06              4  1.254936e+06
2024-02-29  1.221903e+06              3  1.269787e+06
2024-03-31  1.247810e+06              5  1.289663e+06
2024-04-30  1.289938e+06              2  1.305718e+06
2024-05-31  1.337781e+06              3  1.301435e+06
2024-06-30  1.385747e+06              7  1.386918e+06
2024-07-31  1.412705e+06              7  1.441247e+06
2024-08-31  1.437077e+06              7  1.457695e+06
2024-09-30  1.464512e+06              5  1.490906e+06
2024-10-31  1.481353e+06              9  1.398168e+06
2024-11-30  1.482487e+06              7  1.393879e+06
2024-12-31  1.447656e+06              9  1.365789e+06
2025-01-31  1.454124e+06              4  1.357910e+06
2025-02-28  1.386396e+06              4  1.277983e+06
2025-03-31  1.433293e+06              5  1.358542e+06
2025-04-30  1.375708e+06              7  1.405610e+06
2025-05-31  1.393158e+06             10  1.429668e+06
2025-06-30  1.452606e+06              9  1.473935e+06
2025-07-31  1.415126e+06              5  1.430688e+06
2025-08-31  1.393806e+06              5  1.410962e+06
2025-09-30  1.451857e+06              9  1.421605e+06
2025-10-31  1.498627e+06             10  1.485779e+06
2025-11-30  1.517033e+06              9  1.513554e+06
2025-12-31  1.520018e+06              6  1.509317e+06

In [55]:
def compute_cagr(series):
    start = series.iloc[0]
    end = series.iloc[-1]
    years = (series.index[-1] - series.index[0]).days / 365.25
    return (end / start) ** (1 / years) - 1

def compute_volatility(series):
    returns = series.pct_change().dropna()
    return returns.std() * np.sqrt(252)

def compute_max_drawdown(series):
    cum_max = series.cummax()
    drawdown = (series - cum_max) / cum_max
    return drawdown.min()

def compute_sharpe(series):
    returns = series.pct_change().dropna()
    return (returns.mean() / returns.std()) * np.sqrt(252)

In [30]:
def summarize_performance(nav_series):
    return {
        "Final Value": nav_series.iloc[-1],
        "Total Return (%)": (nav_series.iloc[-1] / nav_series.iloc[0] - 1) * 100,
        "CAGR (%)": compute_cagr(nav_series) * 100,
        "Volatility (%)": compute_volatility(nav_series) * 100,
        "Max Drawdown (%)": compute_max_drawdown(nav_series) * 100,
        "Sharpe Ratio": compute_sharpe(nav_series)
    }

In [111]:
portfolio_nav = result.iloc[:, 0]   # your portfolio NAV
benchmark_nav = nifty_curve         # NIFTY ETF NAV

In [112]:
final_table = pd.DataFrame.from_dict(
    {
        "Portfolio": summarize_performance(portfolio_nav),
        "NIFTY ETF": summarize_performance(benchmark_nav)
    },
    orient="index"
)

final_table

,Final Value,Total Return (%),CAGR (%),Volatility (%),Max Drawdown (%),Sharpe Ratio
Portfolio,1.520018e+06,52.074276,15.910640,41.795360,-7.202676,7.681512
NIFTY ETF,1.509317e+06,51.003677,15.622569,51.639672,-14.281399,6.200473

In [ ]:
comparison.to_excel('/content/backtest.xlsx')